services:
  mongodb:
    image: mongo:8.0
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - flowryn-mongodb:/data/db

  redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - flowryn-redis:/data

volumes:
  flowryn-mongodb:
  flowryn-redis: