services:
  mongodb:
    image: mongo:8.0
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "try { rs.status(); } catch (e) { rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'localhost:27017'}]}); }"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - flowryn-mongodb:/data/db

  redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - flowryn-redis:/data

volumes:
  flowryn-mongodb:
  flowryn-redis: