// @vitest-environment jsdom
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import { IntelligenceApp } from './IntelligenceApp';
const api=vi.hoisted(()=>({activatePolicy:vi.fn(),getActivePolicy:vi.fn(async()=>({policy:{_id:'p1',version:1,name:'Default',active:true,configuration:{weights:{},thresholds:{now:70,soon:40},maximumActiveRecommendations:100}}})),getIntelligenceMetrics:vi.fn(async()=>({byType:[{_id:'task.overdue',count:1}],repeatedSignals:0,insufficientData:false})),listPolicies:vi.fn(async()=>({policies:[{_id:'p1',version:1,name:'Default',active:true}]})),listPriority:vi.fn(async()=>({signals:[{_id:'s1',sourceType:'task.overdue',sourceId:'t1',state:'active',score:72,scoreGroup:'now',severity:'high',urgency:'high',impact:'medium',confidence:'high',explanation:'bounded factors',factors:[{key:'criticality',contribution:10,explanation:'unknown contributes 10 points',unknown:true}],lastObservedAt:'2026-10-01T00:00:00.000Z'}],counts:{now:1},total:1})),listRecommendations:vi.fn(async()=>({recommendations:[{_id:'r1',signalId:'s1',type:'reviewTask',explanation:'Review',deepLink:'/projects/p1?task=t1',state:'open',requiredPermission:'member'}]})),recommendationAction:vi.fn(async()=>({})),reconcileIntelligence:vi.fn(async()=>({}))}));
vi.mock('../intelligence-api',()=>api);
const show=(role='owner')=>render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><IntelligenceApp workspaceId="w1" role={role} onNavigate={vi.fn()}/></QueryClientProvider>);
describe('operational intelligence workflows',()=>{afterEach(cleanup);beforeEach(()=>{vi.clearAllMocks();Object.defineProperty(navigator,'onLine',{configurable:true,value:true});});
  it('shows labelled groups, explanations, unknown evidence, source links and advisory actions',async()=>{show();expect(await screen.findByRole('heading',{name:/Now/})).toBeTruthy();fireEvent.click(screen.getByText('Why this is prioritized'));expect(screen.getByText(/Unknown: unknown contributes/)).toBeTruthy();expect(screen.getByRole('button',{name:'Open source workflow'})).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Accept'}));await waitFor(()=>expect(api.recommendationAction).toHaveBeenCalledTimes(1));});
  it('restricts workspace policy tools and recovers visible REST failures',async()=>{api.listPriority.mockRejectedValueOnce(new Error('offline'));show('member');expect(await screen.findByRole('alert')).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'Retry'}));await waitFor(()=>expect(api.listPriority).toHaveBeenCalledTimes(2));expect(screen.queryByRole('heading',{name:'Scoring policy'})).toBeNull();});
});
