import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useState } from 'react';

import { listMembers } from '../api';
import { createDependency, createMonitor, createService, createSlo, getEvaluation, getMonitorHistory, getReliabilityMetrics, listDependencies, listMonitors, listServiceRelationships, listServices, listSlos, updateMonitor, updateService } from '../reliability-api';

function SloRow({ workspaceId, slo }: { workspaceId: string; slo: { _id: string; name: string; objectiveTarget: number; rollingWindowDays: number } }) {
  const evaluation = useQuery({ queryKey: ['slo-evaluation', slo._id], queryFn: () => getEvaluation(workspaceId, slo._id) });
  const value = evaluation.data?.evaluation;
  return <li><strong>{slo.name}</strong><span>{slo.objectiveTarget}% over {slo.rollingWindowDays} days</span><span>{evaluation.isLoading ? 'Calculating…' : evaluation.isError ? 'Unavailable' : value?.state === 'unknown' ? 'Unknown — insufficient data' : `${value?.state}: ${((value?.compliance ?? 0) * 100).toFixed(3)}%; ${((value?.remainingBudget ?? 0) * 100).toFixed(1)}% budget remaining`}</span></li>;
}
export function ReliabilityApp({ workspaceId, role }: { workspaceId: string; role: string }) {
  const client = useQueryClient(); const canManage = role === 'owner' || role === 'admin';
  const [name, setName] = useState(''); const [slug, setSlug] = useState(''); const [selected, setSelected] = useState('');
  const [servicePage, setServicePage] = useState(1);
  const [sloName, setSloName] = useState('Availability'); const [sloTarget, setSloTarget] = useState(99.9); const [sloWindow, setSloWindow] = useState<7 | 28 | 30 | 90>(30);
  const [monitorPage, setMonitorPage] = useState(1);
  const [online, setOnline] = useState(() => navigator.onLine); const [selectedMonitor, setSelectedMonitor] = useState('');
  useEffect(() => { const up = () => setOnline(true); const down = () => setOnline(false); window.addEventListener('online', up); window.addEventListener('offline', down); return () => { window.removeEventListener('online', up); window.removeEventListener('offline', down); }; }, []);
  const [monitorUrl, setMonitorUrl] = useState('https://'); const [monitorEnabled, setMonitorEnabled] = useState(false);
  const [secretHeader, setSecretHeader] = useState('authorization'); const [secretValue, setSecretValue] = useState('');
  const services = useQuery({ queryKey: ['reliability-services', workspaceId, servicePage], queryFn: () => listServices(workspaceId, servicePage) });
  const slos = useQuery({ queryKey: ['reliability-slos', workspaceId], queryFn: () => listSlos(workspaceId) });
  const dependencies = useQuery({ queryKey: ['reliability-dependencies', workspaceId], queryFn: () => listDependencies(workspaceId) });
  const monitors = useQuery({ queryKey: ['reliability-monitors', workspaceId, monitorPage], queryFn: () => listMonitors(workspaceId, monitorPage) });
  const metrics = useQuery({ queryKey: ['reliability-metrics', workspaceId], queryFn: () => getReliabilityMetrics(workspaceId) });
  const members = useQuery({ queryKey: ['members', workspaceId], queryFn: () => listMembers(workspaceId) });
  const ownerId = members.data?.members[0]?.user._id;
  const relationships = useQuery({ queryKey: ['reliability-relationships', workspaceId, selected], queryFn: () => listServiceRelationships(workspaceId, selected), enabled: !!selected });
  const monitorHistory = useQuery({ queryKey: ['reliability-monitor-history', workspaceId, selectedMonitor], queryFn: () => getMonitorHistory(workspaceId, selectedMonitor), enabled: !!selectedMonitor });
  const refresh = () => Promise.all(['services', 'slos', 'dependencies', 'monitors', 'metrics'].map((key) => client.invalidateQueries({ queryKey: [`reliability-${key}`, workspaceId] })));
  const addService = useMutation({ mutationFn: () => createService(workspaceId, { name, slug, description: '', lifecycle: 'active', criticality: 'tier2', ownerIds: [ownerId], projectIds: [], labels: {}, links: [] }), onSuccess: async () => { setName(''); setSlug(''); await refresh(); } });
  const addSlo = useMutation({ mutationFn: () => createSlo(workspaceId, { serviceId: selected, name: sloName, description: 'Successful requests', enabled: true, indicatorType: 'availability', objectiveTarget: sloTarget, rollingWindowDays: sloWindow, dataSource: { type: 'api' }, missingDataPolicy: 'unknown', burnRateAlerts: [] }), onSuccess: refresh });
  const addMonitor = useMutation({ mutationFn: () => createMonitor(workspaceId, { serviceId: selected, name: 'HTTPS health', enabled: monitorEnabled, url: monitorUrl, method: 'GET', intervalSeconds: 300, timeoutMs: 5000, maxRedirects: 1, expectedStatusMin: 200, expectedStatusMax: 299, ...(secretValue ? { secretHeaders: { [secretHeader]: secretValue } } : {}) }), onSuccess: async () => { setMonitorUrl('https://'); setMonitorEnabled(false); setSecretValue(''); await refresh(); } });
  const toggleMonitor = useMutation({ mutationFn: ({ id, enabled }: { id: string; enabled: boolean }) => updateMonitor(workspaceId, id, { enabled }), onSuccess: refresh });
  const changeLifecycle = useMutation({ mutationFn: (lifecycle: 'active' | 'deprecated' | 'retired') => updateService(workspaceId, selected, { lifecycle }), onSuccess: refresh });
  const addDependency = useMutation({ mutationFn: () => { const list = services.data?.services ?? []; return createDependency(workspaceId, { upstreamServiceId: list[0]?._id, downstreamServiceId: list[1]?._id, type: 'runtime', criticality: 'required', description: '', enabled: true }); }, onSuccess: refresh });
  return <main className="workspace-shell">{!online && <p role="status">Offline. Showing cached reliability data; changes will resume after reconnection.</p>}<header><p className="eyebrow">Reliability</p><h1>Service catalog and objectives</h1><p className="muted">Unknown data stays unknown. Error budgets are calculated from server-side SLI samples.</p></header>
    {metrics.isError ? <p role="alert">Reliability metrics are unavailable.</p> : <section className="panel"><h2>Risk overview</h2><p>{metrics.data?.servicesWithoutOwners ?? 0} services without active owners</p><p>{metrics.data?.notice}</p></section>}
    {canManage && <section className="panel"><h2>Add service</h2><form onSubmit={(event) => { event.preventDefault(); addService.mutate(); }}><label>Name<input required value={name} onChange={(e) => setName(e.target.value)} /></label><label>Slug<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={slug} onChange={(e) => setSlug(e.target.value.toLowerCase())} /></label><button disabled={!ownerId || addService.isPending}>Create service</button></form>{addService.isError && <p role="alert">Service creation failed.</p>}</section>}
    <section className="panel"><h2>Services</h2>{services.isLoading ? <p>Loading…</p> : services.isError ? <p role="alert">Services could not be loaded.</p> : <><label>Selected service<select value={selected} onChange={(e) => setSelected(e.target.value)}><option value="">Choose a service</option>{services.data?.services.map((service) => <option key={service._id} value={service._id}>{service.name}</option>)}</select></label><table><thead><tr><th>Service</th><th>Lifecycle</th><th>Criticality</th><th>Owners</th></tr></thead><tbody>{services.data?.services.map((service) => <tr key={service._id}><td>{service.name}</td><td>{service.lifecycle}</td><td>{service.criticality}</td><td>{service.ownerIds.length}</td></tr>)}</tbody></table><p><button disabled={servicePage === 1} onClick={() => setServicePage((page) => page - 1)}>Previous services</button> <button disabled={(services.data?.services.length ?? 0) < 100} onClick={() => setServicePage((page) => page + 1)}>Next services</button></p></>}</section>
    {selected && <section className="panel"><h2>Service detail</h2>{canManage && <label>Lifecycle<select aria-label="Service lifecycle" disabled={changeLifecycle.isPending} value={services.data?.services.find((service) => service._id === selected)?.lifecycle ?? "active"} onChange={(event) => changeLifecycle.mutate(event.target.value as "active" | "deprecated" | "retired")}><option value="active">Active</option><option value="deprecated">Deprecated</option><option value="retired">Retired</option></select></label>}<h3>Relationships</h3>{relationships.isLoading ? <p>Loading…</p> : relationships.isError ? <p role="alert">Relationships unavailable.</p> : relationships.data?.relationships.length ? <ul>{relationships.data.relationships.map((item) => <li key={item._id}>{item.targetType}: {item.targetId}</li>)}</ul> : <p>No linked incidents, alerts, escalations, projects, or status components.</p>}</section>}
    <section className="panel"><h2>Dependencies</h2>{canManage && <button disabled={(services.data?.services.length ?? 0) < 2 || addDependency.isPending} onClick={() => { if (window.confirm('Create a required dependency between the first two services?')) addDependency.mutate(); }}>Add dependency</button>}<table><thead><tr><th>Upstream</th><th>Downstream</th><th>Type</th><th>Impact</th></tr></thead><tbody>{dependencies.data?.dependencies.map((item) => <tr key={item._id}><td>{item.upstreamServiceId}</td><td>{item.downstreamServiceId}</td><td>{item.type}</td><td>{item.criticality}</td></tr>)}</tbody></table></section>
    <section className="panel"><h2>Objectives and error budgets</h2>{canManage && <form onSubmit={(event) => { event.preventDefault(); addSlo.mutate(); }}><label>Objective name<input required maxLength={120} value={sloName} onChange={(event) => setSloName(event.target.value)} /></label><label>Target percent<input type="number" min="0.001" max="99.999" step="0.001" value={sloTarget} onChange={(event) => setSloTarget(Number(event.target.value))} /></label><label>Rolling window<select value={sloWindow} onChange={(event) => setSloWindow(Number(event.target.value) as 7 | 28 | 30 | 90)}>{[7, 28, 30, 90].map((days) => <option key={days} value={days}>{days} days</option>)}</select></label><button disabled={!selected || addSlo.isPending}>Create availability objective</button>{addSlo.isError && <p role="alert">Objective creation failed.</p>}</form>}<ul className="status-list">{slos.data?.slos.map((slo) => <SloRow key={slo._id} workspaceId={workspaceId} slo={slo} />)}</ul></section>
    <section className="panel"><h2>Synthetic monitors</h2><p>Enabling a monitor creates external HTTPS traffic. Secret headers are write-only and never displayed.</p>{canManage && <form onSubmit={(event) => { event.preventDefault(); if (!monitorEnabled || window.confirm(`Enable external checks to ${monitorUrl}?`)) addMonitor.mutate(); }}><label>HTTPS endpoint<input type="url" required pattern="https://.*" value={monitorUrl} onChange={(event) => setMonitorUrl(event.target.value)} /></label><fieldset><legend>Optional one-time secret header</legend><label>Header name<input value={secretHeader} pattern="authorization|x-[a-z0-9-]+" onChange={(event) => setSecretHeader(event.target.value.toLowerCase())} /></label><label>Secret value<input type="password" autoComplete="new-password" value={secretValue} onChange={(event) => setSecretValue(event.target.value)} /></label><p>The stored value cannot be viewed again. Entering a new value rotates it.</p></fieldset><label><input type="checkbox" checked={monitorEnabled} onChange={(event) => setMonitorEnabled(event.target.checked)} /> Enable checks immediately</label><button disabled={!selected || addMonitor.isPending}>Create monitor</button>{addMonitor.isError && <p role="alert">Monitor creation failed. Check the HTTPS destination and try again.</p>}</form>}<ul>{monitors.data?.monitors.map((monitor) => <li key={monitor._id}><button type="button" onClick={() => setSelectedMonitor(monitor._id)}><strong>{monitor.name}</strong></button> - {monitor.health} ({monitor.enabled ? 'enabled' : 'disabled'}) {canManage && <button disabled={toggleMonitor.isPending} onClick={() => { const enabled = !monitor.enabled; if (!enabled || window.confirm(`Enable external checks to ${monitor.url}?`)) toggleMonitor.mutate({ id: monitor._id, enabled }); }}>{monitor.enabled ? 'Disable' : 'Enable'}</button>}</li>)}</ul>{selectedMonitor && <section aria-live="polite"><h3>Execution and recovery timeline</h3>{monitorHistory.isLoading ? <p>Loading…</p> : monitorHistory.isError ? <p role="alert">Execution history unavailable.</p> : monitorHistory.data?.runs.length ? <ol>{monitorHistory.data.runs.map((run) => <li key={run._id}>{new Date(run.scheduledAt).toLocaleString()}: {run.status}, {run.endpointHealthy === undefined ? run.errorCode ?? "unknown" : run.endpointHealthy ? "healthy" : "failed"}{run.latencyMs === undefined ? "" : `, ${run.latencyMs} ms`}</li>)}</ol> : <p>No executions yet.</p>}</section>}<p><button disabled={monitorPage === 1} onClick={() => setMonitorPage((page) => page - 1)}>Previous monitors</button> <button disabled={(monitors.data?.monitors.length ?? 0) < 100} onClick={() => setMonitorPage((page) => page + 1)}>Next monitors</button></p></section>
  </main>;
}
