import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState } from 'react';

import { listMembers } from '../api';
import { createDependency, createMonitor, createService, createSlo, getEvaluation, getReliabilityMetrics, listDependencies, listMonitors, listServices, listSlos, updateMonitor } from '../reliability-api';

function SloRow({ workspaceId, slo }: { workspaceId: string; slo: { _id: string; name: string; objectiveTarget: number; rollingWindowDays: number } }) {
  const evaluation = useQuery({ queryKey: ['slo-evaluation', slo._id], queryFn: () => getEvaluation(workspaceId, slo._id) });
  const value = evaluation.data?.evaluation;
  return <li><strong>{slo.name}</strong><span>{slo.objectiveTarget}% over {slo.rollingWindowDays} days</span><span>{evaluation.isLoading ? 'Calculating…' : evaluation.isError ? 'Unavailable' : value?.state === 'unknown' ? 'Unknown — insufficient data' : `${value?.state}: ${((value?.compliance ?? 0) * 100).toFixed(3)}%; ${((value?.remainingBudget ?? 0) * 100).toFixed(1)}% budget remaining`}</span></li>;
}
export function ReliabilityApp({ workspaceId, role }: { workspaceId: string; role: string }) {
  const client = useQueryClient(); const canManage = role === 'owner' || role === 'admin';
  const [name, setName] = useState(''); const [slug, setSlug] = useState(''); const [selected, setSelected] = useState('');
  const [servicePage, setServicePage] = useState(1);
  const [monitorPage, setMonitorPage] = useState(1);
  const [monitorUrl, setMonitorUrl] = useState('https://'); const [monitorEnabled, setMonitorEnabled] = useState(false);
  const services = useQuery({ queryKey: ['reliability-services', workspaceId, servicePage], queryFn: () => listServices(workspaceId, servicePage) });
  const slos = useQuery({ queryKey: ['reliability-slos', workspaceId], queryFn: () => listSlos(workspaceId) });
  const dependencies = useQuery({ queryKey: ['reliability-dependencies', workspaceId], queryFn: () => listDependencies(workspaceId) });
  const monitors = useQuery({ queryKey: ['reliability-monitors', workspaceId, monitorPage], queryFn: () => listMonitors(workspaceId, monitorPage) });
  const metrics = useQuery({ queryKey: ['reliability-metrics', workspaceId], queryFn: () => getReliabilityMetrics(workspaceId) });
  const members = useQuery({ queryKey: ['members', workspaceId], queryFn: () => listMembers(workspaceId) });
  const ownerId = members.data?.members[0]?.user._id;
  const refresh = () => Promise.all(['services', 'slos', 'dependencies', 'monitors', 'metrics'].map((key) => client.invalidateQueries({ queryKey: [`reliability-${key}`, workspaceId] })));
  const addService = useMutation({ mutationFn: () => createService(workspaceId, { name, slug, description: '', lifecycle: 'active', criticality: 'tier2', ownerIds: [ownerId], projectIds: [], labels: {}, links: [] }), onSuccess: async () => { setName(''); setSlug(''); await refresh(); } });
  const addSlo = useMutation({ mutationFn: () => createSlo(workspaceId, { serviceId: selected, name: 'Availability', description: 'Successful requests', enabled: true, indicatorType: 'availability', objectiveTarget: 99.9, rollingWindowDays: 30, dataSource: { type: 'api' }, missingDataPolicy: 'unknown', burnRateAlerts: [] }), onSuccess: refresh });
  const addMonitor = useMutation({ mutationFn: () => createMonitor(workspaceId, { serviceId: selected, name: 'HTTPS health', enabled: monitorEnabled, url: monitorUrl, method: 'GET', intervalSeconds: 300, timeoutMs: 5000, maxRedirects: 1, expectedStatusMin: 200, expectedStatusMax: 299 }), onSuccess: async () => { setMonitorUrl('https://'); setMonitorEnabled(false); await refresh(); } });
  const toggleMonitor = useMutation({ mutationFn: ({ id, enabled }: { id: string; enabled: boolean }) => updateMonitor(workspaceId, id, { enabled }), onSuccess: refresh });
  const addDependency = useMutation({ mutationFn: () => { const list = services.data?.services ?? []; return createDependency(workspaceId, { upstreamServiceId: list[0]?._id, downstreamServiceId: list[1]?._id, type: 'runtime', criticality: 'required', description: '', enabled: true }); }, onSuccess: refresh });
  return <main className="workspace-shell"><header><p className="eyebrow">Reliability</p><h1>Service catalog and objectives</h1><p className="muted">Unknown data stays unknown. Error budgets are calculated from server-side SLI samples.</p></header>
    {metrics.isError ? <p role="alert">Reliability metrics are unavailable.</p> : <section className="panel"><h2>Risk overview</h2><p>{metrics.data?.servicesWithoutOwners ?? 0} services without active owners</p><p>{metrics.data?.notice}</p></section>}
    {canManage && <section className="panel"><h2>Add service</h2><form onSubmit={(event) => { event.preventDefault(); addService.mutate(); }}><label>Name<input required value={name} onChange={(e) => setName(e.target.value)} /></label><label>Slug<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={slug} onChange={(e) => setSlug(e.target.value.toLowerCase())} /></label><button disabled={!ownerId || addService.isPending}>Create service</button></form>{addService.isError && <p role="alert">Service creation failed.</p>}</section>}
    <section className="panel"><h2>Services</h2>{services.isLoading ? <p>Loading…</p> : services.isError ? <p role="alert">Services could not be loaded.</p> : <><label>Selected service<select value={selected} onChange={(e) => setSelected(e.target.value)}><option value="">Choose a service</option>{services.data?.services.map((service) => <option key={service._id} value={service._id}>{service.name}</option>)}</select></label><table><thead><tr><th>Service</th><th>Lifecycle</th><th>Criticality</th><th>Owners</th></tr></thead><tbody>{services.data?.services.map((service) => <tr key={service._id}><td>{service.name}</td><td>{service.lifecycle}</td><td>{service.criticality}</td><td>{service.ownerIds.length}</td></tr>)}</tbody></table><p><button disabled={servicePage === 1} onClick={() => setServicePage((page) => page - 1)}>Previous services</button> <button disabled={(services.data?.services.length ?? 0) < 100} onClick={() => setServicePage((page) => page + 1)}>Next services</button></p></>}</section>
    <section className="panel"><h2>Dependencies</h2>{canManage && <button disabled={(services.data?.services.length ?? 0) < 2 || addDependency.isPending} onClick={() => { if (window.confirm('Create a required dependency between the first two services?')) addDependency.mutate(); }}>Add dependency</button>}<table><thead><tr><th>Upstream</th><th>Downstream</th><th>Type</th><th>Impact</th></tr></thead><tbody>{dependencies.data?.dependencies.map((item) => <tr key={item._id}><td>{item.upstreamServiceId}</td><td>{item.downstreamServiceId}</td><td>{item.type}</td><td>{item.criticality}</td></tr>)}</tbody></table></section>
    <section className="panel"><h2>Objectives and error budgets</h2>{canManage && <button disabled={!selected || addSlo.isPending} onClick={() => addSlo.mutate()}>Add 99.9% availability objective</button>}<ul className="status-list">{slos.data?.slos.map((slo) => <SloRow key={slo._id} workspaceId={workspaceId} slo={slo} />)}</ul></section>
    <section className="panel"><h2>Synthetic monitors</h2><p>Enabling a monitor creates external HTTPS traffic. Secret headers are write-only and never displayed.</p>{canManage && <form onSubmit={(event) => { event.preventDefault(); if (!monitorEnabled || window.confirm(`Enable external checks to ${monitorUrl}?`)) addMonitor.mutate(); }}><label>HTTPS endpoint<input type="url" required pattern="https://.*" value={monitorUrl} onChange={(event) => setMonitorUrl(event.target.value)} /></label><label><input type="checkbox" checked={monitorEnabled} onChange={(event) => setMonitorEnabled(event.target.checked)} /> Enable checks immediately</label><button disabled={!selected || addMonitor.isPending}>Create monitor</button>{addMonitor.isError && <p role="alert">Monitor creation failed. Check the HTTPS destination and try again.</p>}</form>}<ul>{monitors.data?.monitors.map((monitor) => <li key={monitor._id}><strong>{monitor.name}</strong> - {monitor.health} ({monitor.enabled ? 'enabled' : 'disabled'}) {canManage && <button disabled={toggleMonitor.isPending} onClick={() => { const enabled = !monitor.enabled; if (!enabled || window.confirm(`Enable external checks to ${monitor.url}?`)) toggleMonitor.mutate({ id: monitor._id, enabled }); }}>{monitor.enabled ? 'Disable' : 'Enable'}</button>}</li>)}</ul><p><button disabled={monitorPage === 1} onClick={() => setMonitorPage((page) => page - 1)}>Previous monitors</button> <button disabled={(monitors.data?.monitors.length ?? 0) < 100} onClick={() => setMonitorPage((page) => page + 1)}>Next monitors</button></p></section>
  </main>;
}
