import type { StatusComponentState } from '@flowryn/shared';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useEffect, useState } from 'react';

import { createStatusComponent, createStatusPage, getDeliveryFailures, getMaintenance, getStatusComponents, getStatusMetrics, listStatusPages, publishStatusPage, setComponentStatus, type StatusPage } from '../status-api';

const states: StatusComponentState[] = ['operational', 'degradedPerformance', 'partialOutage', 'majorOutage', 'maintenance'];
function PageManagement({ workspaceId, page, initialMaintenanceId }: { workspaceId: string; page: StatusPage; initialMaintenanceId?: string }) {
  const client = useQueryClient();
  const [componentName, setComponentName] = useState('');
  const [componentSlug, setComponentSlug] = useState('');
  const components = useQuery({ queryKey: ['status-components', page._id], queryFn: () => getStatusComponents(workspaceId, page._id) });
  const metrics = useQuery({ queryKey: ['status-metrics', page._id], queryFn: () => getStatusMetrics(workspaceId, page._id) });
  const failures = useQuery({ queryKey: ['status-deliveries', page._id], queryFn: () => getDeliveryFailures(workspaceId, page._id) });
  const maintenance = useQuery({ queryKey: ['status-maintenance', page._id], queryFn: () => getMaintenance(workspaceId, page._id) });
  useEffect(() => { if (initialMaintenanceId && maintenance.data) document.getElementById(`maintenance-${initialMaintenanceId}`)?.scrollIntoView({ block: 'center' }); }, [initialMaintenanceId, maintenance.data]);
  const health = useMutation({ mutationFn: ({ id, status }: { id: string; status: StatusComponentState }) => setComponentStatus(workspaceId, page._id, id, status), onSuccess: async () => { await Promise.all([client.invalidateQueries({ queryKey: ['status-components', page._id] }), client.invalidateQueries({ queryKey: ['status-metrics', page._id] })]); } });
  const createComponent = useMutation({ mutationFn: () => createStatusComponent(workspaceId, page._id, componentName, componentSlug, (components.data?.components.length ?? 0) + 1), onSuccess: async () => { setComponentName(''); setComponentSlug(''); await client.invalidateQueries({ queryKey: ['status-components', page._id] }); } });
  return <div aria-label={`${page.name} management`}><h3>Component health</h3><form onSubmit={(event) => { event.preventDefault(); createComponent.mutate(); }}><label>Component name<input required value={componentName} onChange={(event) => setComponentName(event.target.value)} /></label><label>Component slug<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={componentSlug} onChange={(event) => setComponentSlug(event.target.value.toLowerCase())} /></label><button disabled={createComponent.isPending}>Add component</button>{createComponent.isError ? <p role="alert">The component could not be created.</p> : null}</form>{components.isLoading ? <p>Loading components…</p> : components.isError ? <p role="alert">Components could not be loaded.</p> : components.data?.components.length ? <ul className="status-list">{components.data.components.map((component) => <li key={component._id}><span><strong>{component.name}</strong><small>{component.hidden ? 'Hidden' : 'Public'} · order {component.order}</small></span><label>Status<span className="sr-only"> for {component.name}</span><select value={component.status} disabled={health.isPending} onChange={(event) => health.mutate({ id: component._id, status: event.target.value as StatusComponentState })}>{states.map((state) => <option key={state}>{state}</option>)}</select></label></li>)}</ul> : <p>No components configured. Add the first component above.</p>}
    <h3>Maintenance</h3>{maintenance.data?.maintenance.length ? <ul>{maintenance.data.maintenance.map((item) => <li id={`maintenance-${item._id}`} key={item._id}><strong>{item.title}</strong> · {item.status} · {new Date(item.scheduledStartAt).toLocaleString()}</li>)}</ul> : <p>{maintenance.isError ? 'Maintenance unavailable.' : 'No maintenance scheduled.'}</p>}
    <h3>Metrics</h3>{metrics.data ? <><p>{metrics.data.subscribers} active subscribers · {metrics.data.publicIncidentsLast365Days} incidents in the last year</p><p className="muted">{metrics.data.availabilityNotice}</p></> : <p>{metrics.isError ? 'Metrics unavailable.' : 'Loading metrics…'}</p>}
    <h3>Delivery failures</h3>{failures.data?.deliveries.length ? <ul>{failures.data.deliveries.map((delivery) => <li key={delivery._id}>{delivery.errorCode} · {delivery.attemptCount} attempts</li>)}</ul> : <p>{failures.isError ? 'Delivery health unavailable.' : 'No delivery failures.'}</p>}</div>;
}
export function StatusAdminApp({ workspaceId, role, initialPageId, initialMaintenanceId }: { workspaceId: string; role: string; initialPageId?: string; initialMaintenanceId?: string }) {
  const client = useQueryClient(); const [name, setName] = useState(''); const [slug, setSlug] = useState(''); const [selected, setSelected] = useState<string | null>(initialPageId ?? null);
  const pages = useQuery({ queryKey: ['status-pages', workspaceId], queryFn: () => listStatusPages(workspaceId) });
  const create = useMutation({ mutationFn: () => createStatusPage(workspaceId, { name, slug, description: '', visibility: 'public', enabled: true, timezone: 'UTC', branding: { primaryColor: '#d7674d' }, supportUrl: null }), onSuccess: async () => { setName(''); setSlug(''); await client.invalidateQueries({ queryKey: ['status-pages', workspaceId] }); } });
  const publish = useMutation({ mutationFn: (id: string) => publishStatusPage(workspaceId, id), onSuccess: () => client.invalidateQueries({ queryKey: ['status-pages', workspaceId] }) });
  if (!['owner', 'admin'].includes(role)) return <main className="workspace-shell"><h1>Status pages</h1><p>Workspace administrator access is required.</p></main>;
  const selectedPage = pages.data?.pages.find((page) => page._id === selected);
  return <main className="workspace-shell status-admin"><header><p className="eyebrow">Subscriber communication</p><h1>Status pages</h1><p className="muted">Publish a deliberately public view of service health.</p></header>
    <section className="panel"><h2>Create a status page</h2><form onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><label>Page name<input required minLength={2} value={name} onChange={(event) => setName(event.target.value)} /></label><label>Public slug<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={slug} onChange={(event) => setSlug(event.target.value.toLowerCase())} /></label><button disabled={create.isPending}>Create page</button>{create.isError ? <p role="alert">The page could not be created.</p> : null}</form></section>
    <section className="panel"><h2>Your pages</h2>{pages.isLoading ? <p>Loading…</p> : pages.isError ? <p role="alert">Status pages could not be loaded.</p> : pages.data?.pages.length ? <ul className="status-list">{pages.data.pages.map((page) => <li key={page._id}><span><strong>{page.name}</strong><small>/status/{page.slug} · {page.visibility}</small></span><span><button onClick={() => setSelected(page._id)} aria-expanded={selected === page._id}>Manage</button>{page.publishedAt ? <a href={`/status/${page.slug}`}>View public page</a> : <button onClick={() => { if (window.confirm(`Publish “${page.name}”? Its name, description, branding, components, incidents, and maintenance will become public.`)) publish.mutate(page._id); }}>Review and publish</button>}</span></li>)}</ul> : <p>No status pages yet.</p>}{selectedPage ? <PageManagement workspaceId={workspaceId} page={selectedPage} initialMaintenanceId={initialMaintenanceId} /> : null}</section>
  </main>;
}
