import { createHash, randomUUID } from 'node:crypto';

import { intelligenceSignalTypes, scheduleSchema, type IntelligencePolicyInput, type IntelligenceSignalType } from '@flowryn/shared';
import mongoose from 'mongoose';

import { AutomationRunModel, OutboxEventModel } from '../automation/models.js';
import { automationActorId } from '../automation/principal.js';
import { IncidentModel } from '../models/Incident.js';
import { TaskModel } from '../models/Task.js';
import { UserModel } from '../models/User.js';
import { WorkspaceModel } from '../models/Workspace.js';
import { WorkspaceMemberModel } from '../models/WorkspaceMember.js';
import { AlertModel, OverrideModel, ScheduleModel } from '../oncall/models.js';
import { calculateOncall } from '../oncall/schedules.js';
import { publishRealtimeEvent } from '../realtime/gateway.js';
import { ServiceLevelObjectiveModel, ServiceModel, SloEvaluationModel, SyntheticMonitorModel, SyntheticMonitorRunModel } from '../reliability/models.js';
import { MaintenanceModel } from '../status/models.js';

import { IntelligenceCheckpointModel, IntelligenceEvaluationModel, IntelligencePolicyModel, IntelligenceRecommendationModel, IntelligenceScoreSnapshotModel, OperationalSignalModel } from './models.js';

export const defaultPolicy: IntelligencePolicyInput = { name: 'Secure default', weights: { severity: 30, urgency: 25, criticality: 20, impact: 15, confidence: 10 }, thresholds: { now: 70, soon: 40 }, includedSignalTypes: ['task.overdue', 'task.blocked', 'incident.highSeverity', 'alert.unacknowledged', 'alert.escalating', 'slo.breached', 'slo.budgetDepleted', 'monitor.repeatedFailure', 'automation.deadLetter', 'monitor.deadLetter', 'oncall.coverageGap', 'maintenance.upcoming', 'maintenance.overdue', 'service.ownerlessCritical'], criticality: { tier1: 1, tier2: .75, tier3: .45, tier4: .2 }, ageBandsHours: [1, 4, 24, 72], notificationThreshold: 80, digest: 'hourly', quietHours: null, maximumActiveRecommendations: 100 };
export const ensureActivePolicy = async (workspaceId: string, actorId?: string) => {
  const current = await IntelligencePolicyModel.findOne({ workspaceId, active: true }); if (current) return current;
  try { return await IntelligencePolicyModel.create({ workspaceId, version: 1, name: defaultPolicy.name, configuration: defaultPolicy, createdBy: actorId ?? automationActorId, activatedBy: actorId ?? automationActorId, active: true, activatedAt: new Date() }); }
  catch { return IntelligencePolicyModel.findOne({ workspaceId, active: true }).orFail(); }
};
type Classification = 'low' | 'medium' | 'high' | 'critical' | 'unknown';
const levels: Record<Classification, number> = { unknown: .5, low: .2, medium: .5, high: .75, critical: 1 };
export const calculateScore = (input: { severity: Classification; urgency: Classification; criticality?: keyof IntelligencePolicyInput['criticality']; impact: Classification; confidence: Classification }, policy: IntelligencePolicyInput) => {
  const values = { severity: levels[input.severity], urgency: levels[input.urgency], criticality: input.criticality ? policy.criticality[input.criticality] : .5, impact: levels[input.impact], confidence: levels[input.confidence] };
  const factors = (Object.keys(values) as Array<keyof typeof values>).map((key) => ({ key, value: values[key], weight: policy.weights[key], contribution: Math.round(values[key] * policy.weights[key] * 100) / 100, explanation: `${key} contributes ${Math.round(values[key] * policy.weights[key] * 100) / 100} points`, unknown: key === 'criticality' && !input.criticality }));
  const score = Math.max(0, Math.min(100, Math.round(factors.reduce((sum, factor) => sum + factor.contribution, 0))));
  return { score, factors, group: score >= policy.thresholds.now ? 'now' : score >= policy.thresholds.soon ? 'soon' : 'watch', explanation: factors.map((f) => f.explanation).join('; ') } as const;
};

type Candidate = { type: IntelligenceSignalType; id: string; revision: string; scoreRevision?: string; severity: Classification; urgency: Classification; impact: Classification; confidence: Classification; criticality?: keyof IntelligencePolicyInput['criticality']; refs?: Record<string, unknown>; assigneeIds?: unknown[]; facts: Record<string, string | number | boolean | null>; recommendation: string; link: string };
const safeDate = (value: unknown) => value instanceof Date ? value.toISOString() : String(value ?? '');
const candidatesFor = async (workspaceId: string, now: Date): Promise<{ items: Candidate[]; incompleteTypes: Set<string> }> => {
  const [tasks, incidents, alerts, evaluations, monitors, monitorDead, automationDead, schedules, maintenance, services, memberIds, activeSlos, activeMonitorIds] = await Promise.all([
    TaskModel.find({ workspaceId, status: { $ne: 'done' }, $or: [{ dueDate: { $lt: now } }, { blocked: true }] }).select('_id projectId assigneeId priority blocked dueDate updatedAt').limit(500).lean(),
    IncidentModel.find({ workspaceId, archivedAt: null, status: { $ne: 'resolved' }, severity: { $in: ['sev1', 'sev2'] } }).select('_id severity commanderId responderIds linkedProjectIds declaredAt acknowledgedAt updatedAt').limit(500).lean(),
    AlertModel.find({ workspaceId, status: 'open' }).select('_id severity serviceId projectId escalationPolicyId createdAt updatedAt').limit(500).lean(),
    SloEvaluationModel.aggregate([{ $match: { workspaceId: new mongoose.Types.ObjectId(workspaceId) } }, { $sort: { windowEnd: -1 } }, { $group: { _id: '$sloId', evaluation: { $first: '$$ROOT' } } }, { $replaceRoot: { newRoot: '$evaluation' } }, { $limit: 501 }]),
    SyntheticMonitorModel.find({ workspaceId, archivedAt: null, enabled: true, failureCount: { $gte: 3 } }).select('_id serviceId failureCount configVersion updatedAt').limit(500).lean(),
    SyntheticMonitorRunModel.find({ workspaceId, status: 'deadLetter' }).select('_id monitorId serviceId configVersion updatedAt').limit(500).lean(),
    Promise.all([OutboxEventModel.find({ workspaceId, status: 'dead' }).select('_id eventType updatedAt').limit(200).lean(), AutomationRunModel.find({ workspaceId, status: { $in: ['failed', 'partiallyFailed'] } }).select('_id updatedAt').limit(200).lean(), IntelligenceEvaluationModel.find({ workspaceId, status: 'dead' }).select('_id sourceType updatedAt').limit(100).lean()]).then(([a,b,c]) => ({ items: [...a, ...b, ...c], truncated: a.length === 200 || b.length === 200 || c.length === 100 })),
    ScheduleModel.find({ workspaceId, archivedAt: null, enabled: true }).select('_id name description enabled timezone allowSelfOverrides layers version updatedAt').limit(200).lean(),
    MaintenanceModel.find({ workspaceId, status: { $in: ['scheduled', 'inProgress'] }, scheduledStartAt: { $lte: new Date(now.getTime() + 24 * 3600_000) } }).select('_id status scheduledStartAt scheduledEndAt updatedAt').limit(500).lean(),
    ServiceModel.find({ workspaceId, archivedAt: null, criticality: { $in: ['tier1', 'tier2'] } }).select('_id ownerIds projectIds criticality version updatedAt').limit(500).lean(),
    WorkspaceMemberModel.find({ workspaceId, disabled: { $ne: true } }).distinct('userId'),
    ServiceLevelObjectiveModel.find({ workspaceId, archivedAt: null, enabled: true }).select('_id version').limit(500).lean(),
    SyntheticMonitorModel.find({ workspaceId, archivedAt: null, enabled: true }).distinct('_id'),
  ]);
  const linkedServiceIds = [...new Set([...alerts.map((item) => item.serviceId), ...evaluations.map((item) => item.serviceId), ...monitors.map((item) => item.serviceId)].filter((id) => mongoose.isValidObjectId(id)).map(String))];
  const linkedServices = await ServiceModel.find({ workspaceId, _id: { $in: linkedServiceIds } }).select('_id criticality version updatedAt').limit(1500).lean();
  const serviceById = new Map(linkedServices.map((service) => [String(service._id), service]));
  const serviceScore = (serviceId: unknown) => { const service = serviceById.get(String(serviceId)); return service ? { criticality: service.criticality as keyof IntelligencePolicyInput['criticality'], scoreRevision: `service:${service.version}:${safeDate(service.updatedAt)}` } : {}; };
  const activeUsers = await UserModel.find({ _id: { $in: memberIds }, status: 'active' }).distinct('_id'); const memberSet = new Set(activeUsers.map(String)); const activeSloVersions = new Map(activeSlos.map((item) => [String(item._id), item.version])); const activeMonitorSet = new Set(activeMonitorIds.map(String)); const result: Candidate[] = [];
  for (const x of tasks) { if (x.dueDate && x.dueDate < now) { const ageHours = Math.min(8760, Math.floor((now.getTime() - x.dueDate.getTime()) / 3600_000)); result.push({ type: 'task.overdue', id: String(x._id), revision: safeDate(x.updatedAt), scoreRevision: `age:${ageHours}`, severity: x.priority === 'urgent' ? 'critical' : x.priority === 'high' ? 'high' : 'medium', urgency: ageHours >= 24 ? 'high' : 'medium', impact: 'medium', confidence: 'high', refs: { taskId: x._id, projectId: x.projectId }, assigneeIds: x.assigneeId ? [x.assigneeId] : [], facts: { dueAt: safeDate(x.dueDate), overdueHours: ageHours, priority: x.priority }, recommendation: 'reviewTask', link: `/projects/${x.projectId}?task=${x._id}` }); } if (x.blocked) result.push({ type: 'task.blocked', id: String(x._id), revision: safeDate(x.updatedAt), severity: x.priority === 'urgent' ? 'critical' : 'high', urgency: 'high', impact: 'high', confidence: 'high', refs: { taskId: x._id, projectId: x.projectId }, assigneeIds: x.assigneeId ? [x.assigneeId] : [], facts: { priority: x.priority, blocked: true }, recommendation: 'reviewTask', link: `/projects/${x.projectId}?task=${x._id}` }); }
  for (const x of incidents) result.push({ type: 'incident.highSeverity', id: String(x._id), revision: safeDate(x.updatedAt), severity: x.severity === 'sev1' ? 'critical' : 'high', urgency: x.acknowledgedAt ? 'high' : 'critical', impact: 'critical', confidence: 'high', refs: { incidentId: x._id, projectId: x.linkedProjectIds?.[0] }, assigneeIds: [x.commanderId, ...(x.responderIds ?? [])].filter(Boolean), facts: { severity: x.severity, acknowledged: !!x.acknowledgedAt, declaredAt: safeDate(x.declaredAt) }, recommendation: x.commanderId ? 'joinIncident' : 'assignIncidentCommander', link: `/incidents/${x._id}` });
  for (const x of alerts) result.push({ type: x.escalationPolicyId ? 'alert.escalating' : 'alert.unacknowledged', id: String(x._id), revision: safeDate(x.updatedAt), ...serviceScore(x.serviceId), severity: x.severity === 'sev1' ? 'critical' : x.severity === 'sev2' ? 'high' : 'medium', urgency: 'high', impact: 'high', confidence: 'high', refs: { alertId: x._id, ...(mongoose.isValidObjectId(x.serviceId) ? { serviceId: x.serviceId } : {}), projectId: x.projectId }, facts: { severity: x.severity, escalating: !!x.escalationPolicyId }, recommendation: 'reviewAlert', link: `/oncall?alert=${x._id}` });
  const seenSlo = new Set<string>(); for (const x of evaluations) { const key = String(x.sloId); if (activeSloVersions.get(key) !== x.sloVersion || seenSlo.has(key)) continue; seenSlo.add(key); if (!x.breaching && (x.remainingBudget == null || x.remainingBudget > 0)) continue; result.push({ type: (x.remainingBudget ?? 1) <= 0 ? 'slo.budgetDepleted' : 'slo.breached', id: key, revision: `${x.sloVersion}:${safeDate(x.windowEnd)}`, ...serviceScore(x.serviceId), severity: (x.remainingBudget ?? 1) <= 0 ? 'critical' : 'high', urgency: 'high', impact: 'high', confidence: (x.total ?? 0) > 0 ? 'high' : 'unknown', refs: { sloId: x.sloId, serviceId: x.serviceId }, facts: { sloVersion: x.sloVersion ?? 0, windowEnd: safeDate(x.windowEnd), remainingBudget: x.remainingBudget ?? null, shortBurnRate: x.shortBurnRate ?? null, longBurnRate: x.longBurnRate ?? null }, recommendation: 'reviewSlo', link: `/reliability?service=${x.serviceId}&slo=${x.sloId}` }); }
  for (const x of monitors) result.push({ type: 'monitor.repeatedFailure', id: String(x._id), revision: `${x.configVersion}:${safeDate(x.updatedAt)}`, ...serviceScore(x.serviceId), severity: x.failureCount >= 5 ? 'critical' : 'high', urgency: 'high', impact: 'high', confidence: 'high', refs: { serviceId: x.serviceId }, facts: { failureCount: x.failureCount, configVersion: x.configVersion }, recommendation: 'investigateMonitor', link: `/reliability?monitor=${x._id}` });
  for (const x of monitorDead) if (activeMonitorSet.has(String(x.monitorId))) result.push({ type: 'monitor.deadLetter', id: String(x._id), revision: safeDate(x.updatedAt), severity: 'high', urgency: 'high', impact: 'medium', confidence: 'high', refs: { serviceId: x.serviceId }, facts: { configVersion: x.configVersion ?? 0 }, recommendation: 'reviewDeadLetter', link: `/reliability?run=${x._id}` });
  for (const x of automationDead.items) result.push({ type: 'automation.deadLetter', id: String(x._id), revision: safeDate(x.updatedAt), severity: 'high', urgency: 'medium', impact: 'medium', confidence: 'high', facts: {}, recommendation: 'sourceType' in x ? 'retryDeadLetter' : 'reviewDeadLetter', link: `/automation?dead=${x._id}` });
  const overrides = await OverrideModel.find({ workspaceId, scheduleId: { $in: schedules.map((item) => item._id) }, cancelledAt: null, startsAt: { $lte: now }, endsAt: { $gt: now } }).limit(1000).lean();
  for (const x of schedules) { const input = scheduleSchema.parse({ name: x.name, description: x.description ?? '', enabled: x.enabled, timezone: x.timezone, allowSelfOverrides: x.allowSelfOverrides ?? false, layers: x.layers }); const resolved = calculateOncall(input, now, memberSet, overrides.filter((item) => String(item.scheduleId) === String(x._id)).map((item) => ({ ...item, id: String(item._id), scheduleId: String(item.scheduleId), replacementUserId: String(item.replacementUserId), originalUserId: item.originalUserId ? String(item.originalUserId) : undefined, startsAt: item.startsAt.toISOString(), endsAt: item.endsAt.toISOString(), reason: item.reason ?? '' }))); const coveredLayers = resolved.filter((layer) => layer.userId).length; if (coveredLayers === 0) result.push({ type: 'oncall.coverageGap', id: String(x._id), revision: `${x.version}:${safeDate(x.updatedAt)}`, severity: 'high', urgency: 'high', impact: 'high', confidence: 'high', facts: { configuredLayers: resolved.length, coveredLayers }, recommendation: 'reviewCoverageGap', link: `/oncall?schedule=${x._id}` }); }
  for (const x of maintenance) { const overdue = x.scheduledEndAt && x.scheduledEndAt < now && x.status !== 'completed'; result.push({ type: overdue ? 'maintenance.overdue' : 'maintenance.upcoming', id: String(x._id), revision: safeDate(x.updatedAt), severity: overdue ? 'high' : 'medium', urgency: overdue ? 'critical' : 'medium', impact: 'medium', confidence: 'high', facts: { status: x.status, scheduledStartAt: safeDate(x.scheduledStartAt), scheduledEndAt: safeDate(x.scheduledEndAt) }, recommendation: 'reviewMaintenance', link: `/status?maintenance=${x._id}` }); }
  for (const x of services) if (!(x.ownerIds ?? []).some((id) => memberSet.has(String(id)))) result.push({ type: 'service.ownerlessCritical', id: String(x._id), revision: `${x.version}:${safeDate(x.updatedAt)}`, severity: x.criticality === 'tier1' ? 'critical' : 'high', urgency: 'high', criticality: x.criticality as 'tier1'|'tier2', impact: 'critical', confidence: 'high', refs: { serviceId: x._id, projectId: x.projectIds?.[0] }, facts: { criticality: x.criticality ?? 'unknown' }, recommendation: 'assignServiceOwner', link: `/reliability?service=${x._id}` });
  const incompleteTypes = new Set<string>();
  const mark = (full: boolean, ...types: IntelligenceSignalType[]) => { if (full) types.forEach((type) => incompleteTypes.add(type)); };
  mark(tasks.length === 500, 'task.overdue', 'task.blocked'); mark(incidents.length === 500, 'incident.highSeverity'); mark(alerts.length === 500, 'alert.unacknowledged', 'alert.escalating'); mark(evaluations.length > 500 || activeSlos.length === 500, 'slo.breached', 'slo.budgetDepleted'); mark(monitors.length === 500, 'monitor.repeatedFailure'); mark(monitorDead.length === 500, 'monitor.deadLetter'); mark(automationDead.truncated, 'automation.deadLetter'); mark(schedules.length === 200 || overrides.length === 1000, 'oncall.coverageGap'); mark(maintenance.length === 500, 'maintenance.upcoming', 'maintenance.overdue'); mark(services.length === 500, 'service.ownerlessCritical');
  if (result.length > 2000) intelligenceSignalTypes.forEach((type) => incompleteTypes.add(type));
  return { items: result.slice(0, 2000), incompleteTypes };
};

export const sourceConditionCurrent = async (signal: { workspaceId: unknown; sourceType: string; sourceId: string; sourceRevision: string }, now = new Date()) => (await candidatesFor(String(signal.workspaceId), now)).items.some((candidate) => candidate.type === signal.sourceType && candidate.id === signal.sourceId && candidate.revision === signal.sourceRevision);

const recommendationPermission: Record<string, string> = { assignIncidentCommander: 'incident.command', retryDeadLetter: 'admin', assignServiceOwner: 'admin' };
const reconcileWorkspaceUnlocked = async (workspaceId: string, now: Date, leaseOwner: string, renewEvaluationLease?: () => Promise<void>) => {
  const renewLease = async () => { const renewed = await IntelligenceCheckpointModel.updateOne({ _id: `workspace:${workspaceId}`, leaseOwner }, { $set: { leaseExpiresAt: new Date(Date.now() + 120_000) } }); if (renewed.matchedCount !== 1) throw new Error('Reconciliation lease lost'); await renewEvaluationLease?.(); };
  const policyDoc = await ensureActivePolicy(workspaceId); const policy = policyDoc.configuration as IntelligencePolicyInput;
  const reopened = await IntelligenceRecommendationModel.updateMany({ workspaceId, state: 'snoozed', snoozedUntil: { $lte: now }, expiresAt: { $gt: now } }, { $set: { state: 'open' }, $unset: { snoozedUntil: 1 } });
  const scan = await candidatesFor(workspaceId, now); const candidates = scan.items.filter((x) => policy.includedSignalTypes.includes(x.type)); const observed = new Set<string>();
  let changed = 0;
  for (const item of candidates) {
    await renewLease();
    const key = `${item.type}:${item.id}`; observed.add(key); const scored = calculateScore(item, policy); const previous = await OperationalSignalModel.findOne({ workspaceId, deduplicationKey: key }).select('score state sourceRevision scoreRevision policyVersion');
    const unchanged = previous?.sourceRevision === item.revision && (previous.scoreRevision ?? '') === (item.scoreRevision ?? '') && previous.state === 'active' && previous.policyVersion === policyDoc.version;
    const signal = unchanged ? previous : await OperationalSignalModel.findOneAndUpdate({ workspaceId, deduplicationKey: key }, { $set: { sourceType: item.type, sourceId: item.id, ...item.refs, assigneeIds: item.assigneeIds ?? [], state: 'active', severity: item.severity, urgency: item.urgency, impact: item.impact, confidence: item.confidence, lastObservedAt: now, resolvedAt: null, sourceRevision: item.revision, scoreRevision: item.scoreRevision, facts: item.facts, score: scored.score, scoreGroup: scored.group, factors: scored.factors, explanation: scored.explanation, policyVersion: policyDoc.version, expiresAt: new Date(now.getTime() + 400 * 86400_000) }, $setOnInsert: { detectedAt: now }, $inc: { observationVersion: 1 } }, { upsert: true, new: true });
    if (unchanged) await OperationalSignalModel.updateOne({ _id: signal!._id }, { $set: { lastObservedAt: now, expiresAt: new Date(now.getTime() + 400 * 86400_000) } });
    else { changed++; await IntelligenceScoreSnapshotModel.updateOne({ workspaceId, signalId: signal!._id, sourceRevision: `${item.revision}:${item.scoreRevision ?? ""}`, policyVersion: policyDoc.version }, { $setOnInsert: { score: scored.score, scoreGroup: scored.group, factors: scored.factors, explanation: scored.explanation, evaluatedAt: now, expiresAt: new Date(now.getTime() + 400 * 86400_000) } }, { upsert: true }); }
    const recommendationKey = `${key}:${item.recommendation}`; const existingRecommendation = await IntelligenceRecommendationModel.findOne({ workspaceId, deduplicationKey: recommendationKey }).select('sourceVersion policyVersion state staleReason');
    await IntelligenceRecommendationModel.updateMany({ workspaceId, signalId: signal!._id, deduplicationKey: { $ne: recommendationKey }, $or: [{ state: { $in: ['open', 'accepted', 'snoozed'] } }, { state: 'stale', staleReason: 'capacity' }] }, { $set: { state: 'stale', staleAt: now, staleReason: 'source' } });
    if (!existingRecommendation || existingRecommendation.sourceVersion !== item.revision || existingRecommendation.policyVersion !== policyDoc.version || (existingRecommendation.state === 'stale' && existingRecommendation.staleReason === 'source') || previous?.state !== 'active') await IntelligenceRecommendationModel.findOneAndUpdate({ workspaceId, deduplicationKey: recommendationKey }, { $set: { signalId: signal._id, type: item.recommendation, explanation: `Review ${item.type.replaceAll('.', ' ')}`, facts: item.facts, requiredPermission: recommendationPermission[item.recommendation] ?? 'member', preconditions: ['source remains active', 'membership remains active'], deepLink: item.link, state: 'open', policyVersion: policyDoc.version, sourceVersion: item.revision, expiresAt: new Date(now.getTime() + 90 * 86400_000) }, $unset: { acceptedAt: 1, dismissedAt: 1, snoozedUntil: 1, completedAt: 1, staleAt: 1, staleReason: 1 } }, { upsert: true });
    if (!unchanged) publishRealtimeEvent({ workspaceId, actorId: automationActorId, entityId: signal.id, type: previous ? previous.score === signal.score ? 'intelligence.signalUpdated' : 'intelligence.priorityChanged' : 'intelligence.signalCreated', payload: {} });
  }
  const active = await OperationalSignalModel.find({ workspaceId, state: 'active' }).select('_id deduplicationKey sourceType').limit(2500);
  await renewLease();
  await IntelligenceRecommendationModel.updateMany({ workspaceId, state: { $in: ['open', 'accepted', 'snoozed'] }, expiresAt: { $lte: now } }, { $set: { state: 'stale', staleAt: now, staleReason: 'expired' } });
  const resolvedIds = active.filter((x) => !scan.incompleteTypes.has(x.sourceType) && !observed.has(x.deduplicationKey)).map((x) => x._id);
  if (resolvedIds.length) { await OperationalSignalModel.updateMany({ _id: { $in: resolvedIds }, state: 'active' }, { $set: { state: 'resolved', resolvedAt: now } }); await IntelligenceRecommendationModel.updateMany({ workspaceId, signalId: { $in: resolvedIds }, state: { $in: ['open', 'accepted', 'snoozed'] } }, { $set: { state: 'stale', staleAt: now, staleReason: 'source' } }); for (const id of resolvedIds) publishRealtimeEvent({ workspaceId, actorId: automationActorId, entityId: String(id), type: 'intelligence.signalResolved', payload: {} }); }
  const recommendationOverflow = await IntelligenceRecommendationModel.find({ workspaceId, state: 'open' }).sort({ updatedAt: -1, _id: 1 }).skip(policy.maximumActiveRecommendations).select('_id');
  if (recommendationOverflow.length) await IntelligenceRecommendationModel.updateMany({ _id: { $in: recommendationOverflow.map((item) => item._id) } }, { $set: { state: 'stale', staleAt: now, staleReason: 'capacity' } });
  const openCount = await IntelligenceRecommendationModel.countDocuments({ workspaceId, state: 'open' }); const availableSlots = Math.max(0, policy.maximumActiveRecommendations - openCount); if (availableSlots) { const activeSignalIds = await OperationalSignalModel.find({ workspaceId, state: 'active' }).distinct('_id'); const refill = await IntelligenceRecommendationModel.find({ workspaceId, state: 'stale', staleReason: 'capacity', signalId: { $in: activeSignalIds } }).sort({ updatedAt: 1, _id: 1 }).limit(availableSlots).select('_id'); if (refill.length) await IntelligenceRecommendationModel.updateMany({ _id: { $in: refill.map((item) => item._id) } }, { $set: { state: 'open', expiresAt: new Date(now.getTime() + 90 * 86400_000) }, $unset: { staleAt: 1, staleReason: 1 } }); }
  const overflow = await OperationalSignalModel.find({ workspaceId, state: 'active' }).sort({ score: -1, detectedAt: 1, _id: 1 }).skip(2000).select('_id'); if (overflow.length) await OperationalSignalModel.updateMany({ _id: { $in: overflow.map((x) => x._id) } }, { $set: { state: 'stale', resolvedAt: now } });
  const checkpoint = await IntelligenceCheckpointModel.updateOne({ _id: `workspace:${workspaceId}`, leaseOwner }, { $set: { lastRunAt: now } }); if (checkpoint.matchedCount !== 1) throw new Error('Reconciliation lease lost');
  if (changed || resolvedIds.length || reopened.modifiedCount) publishRealtimeEvent({ workspaceId, actorId: automationActorId, type: 'intelligence.queueChanged', payload: {} });
  return { observed: candidates.length, resolved: resolvedIds.length };
};

export const reconcileWorkspace = async (workspaceId: string, now = new Date(), renewEvaluationLease?: () => Promise<void>) => {
  const key = `workspace:${workspaceId}`; const owner = randomUUID(); const leaseNow = new Date();
  await IntelligenceCheckpointModel.updateOne({ _id: key }, { $setOnInsert: { lastRunAt: new Date(0) } }, { upsert: true });
  const lock = await IntelligenceCheckpointModel.findOneAndUpdate({ _id: key, $or: [{ leaseExpiresAt: null }, { leaseExpiresAt: { $lte: leaseNow } }] }, { $set: { leaseOwner: owner, leaseExpiresAt: new Date(leaseNow.getTime() + 120_000) } }, { new: true });
  if (!lock) return { observed: 0, resolved: 0, skipped: true };
  try { return await reconcileWorkspaceUnlocked(workspaceId, now, owner, renewEvaluationLease); }
  finally { await IntelligenceCheckpointModel.updateOne({ _id: key, leaseOwner: owner }, { $unset: { leaseOwner: 1, leaseExpiresAt: 1 } }); }
};

export const queueEvaluation = async (workspaceId: string, sourceType: string, sourceId: string, sourceRevision: string) => {
  const hash = createHash('sha256').update(`${sourceType}:${sourceId}:${sourceRevision}`).digest('hex');
  return IntelligenceEvaluationModel.findOneAndUpdate({ workspaceId, workKey: hash }, { $setOnInsert: { sourceType, sourceId, sourceRevision, status: 'pending', availableAt: new Date() } }, { upsert: true, new: true });
};
const schedulePeriodicReconciliation = async (now: Date) => { const cursorState = await IntelligenceCheckpointModel.findById('reconciliation:cursor').lean(); let workspaces = await WorkspaceModel.find(cursorState?.cursor ? { _id: { $gt: cursorState.cursor } } : {}).select('_id').sort({ _id: 1 }).limit(500).lean(); if (!workspaces.length && cursorState?.cursor) workspaces = await WorkspaceModel.find().select('_id').sort({ _id: 1 }).limit(500).lean(); if (!workspaces.length) return 0; const checkpoints = await IntelligenceCheckpointModel.find({ _id: { $in: workspaces.map((item) => `workspace:${item._id}`) } }).select('_id lastRunAt').lean(); const byId = new Map(checkpoints.map((item) => [item._id, item.lastRunAt])); let scheduled = 0; for (const workspace of workspaces) { const workspaceId = String(workspace._id); const lastRunAt = byId.get(`workspace:${workspaceId}`); if (!lastRunAt || now.getTime() - lastRunAt.getTime() >= 300_000) { await queueEvaluation(workspaceId, 'reconciliation', workspaceId, now.toISOString().slice(0, 16)); scheduled++; } } await IntelligenceCheckpointModel.findByIdAndUpdate('reconciliation:cursor', { $set: { cursor: workspaces.at(-1)!._id, lastRunAt: now } }, { upsert: true }); return scheduled; };
export const processIntelligenceWork = async (now = new Date(), owner = 'intelligence-worker') => {
  const scheduled = await schedulePeriodicReconciliation(now);
  const leaseOwner = `${owner}:${randomUUID()}`; const leaseExpiresAt = new Date(now.getTime() + 60_000);
  const job = await IntelligenceEvaluationModel.findOneAndUpdate({ status: { $in: ['pending', 'processing'] }, availableAt: { $lte: now }, $or: [{ leaseExpiresAt: null }, { leaseExpiresAt: { $lte: now } }] }, { $set: { status: 'processing', leaseOwner, leaseExpiresAt }, $inc: { attemptCount: 1 } }, { sort: { availableAt: 1, _id: 1 }, new: true });
  if (!job) return scheduled > 0;
  try { const renewEvaluationLease = async () => { const renewed = await IntelligenceEvaluationModel.updateOne({ _id: job._id, leaseOwner, status: 'processing' }, { $set: { leaseExpiresAt: new Date(Date.now() + 60_000) } }); if (renewed.matchedCount !== 1) throw new Error('Evaluation lease lost'); }; const result = await reconcileWorkspace(String(job.workspaceId), now, renewEvaluationLease); if ('skipped' in result && result.skipped) { await IntelligenceEvaluationModel.updateOne({ _id: job._id, leaseOwner }, { $set: { status: 'pending', availableAt: new Date(now.getTime() + 5000) }, $unset: { leaseOwner: 1, leaseExpiresAt: 1 } }); return true; } const completed = await IntelligenceEvaluationModel.updateOne({ _id: job._id, leaseOwner, status: 'processing' }, { $set: { status: 'completed', completedAt: now }, $unset: { leaseOwner: 1, leaseExpiresAt: 1, error: 1 } }); if (completed.matchedCount !== 1) throw new Error('Evaluation lease lost'); }
  catch { const dead = job.attemptCount >= 5; await IntelligenceEvaluationModel.updateOne({ _id: job._id, leaseOwner }, { $set: { status: dead ? 'dead' : 'pending', availableAt: new Date(now.getTime() + Math.min(300_000, 1000 * 2 ** job.attemptCount)), error: 'EVALUATION_FAILED' }, $unset: { leaseOwner: 1, leaseExpiresAt: 1 } }); }
  return true;
};
