import { randomUUID } from 'node:crypto';

import { dependencyInputSchema, monitorInputSchema, relationshipInputSchema, reliabilityQuerySchema, serviceInputSchema, sliBatchSchema, sloInputSchema, statusIdSchema } from '@flowryn/shared';
import { Router } from 'express';
import type { Request } from 'express';
import mongoose from 'mongoose';
import type { z } from 'zod';

import { encryptSecret } from '../automation/security.js';
import { assertIncident, IncidentError } from '../incidents/service.js';
import { requireAuth, requireWorkspaceRole } from '../middleware/auth.js';
import { ActivityModel } from '../models/Activity.js';
import { IncidentModel } from '../models/Incident.js';
import { ProjectModel } from '../models/Project.js';
import { UserModel } from '../models/User.js';
import { WorkspaceMemberModel } from '../models/WorkspaceMember.js';
import { AlertModel, PolicyModel } from '../oncall/models.js';
import { ReliabilityGraphLockModel, ServiceDependencyModel, ServiceLevelObjectiveModel, ServiceModel, ServiceRelationshipModel, SliSampleModel, SloEvaluationModel, SyntheticMonitorModel, SyntheticMonitorRunModel } from '../reliability/models.js';
import { assertSafeMonitorUrl, dependencyImpact, normalizeServiceSlug, processReliabilityWork, storeEvaluation, wouldCreateCycle } from '../reliability/service.js';
import { StatusComponentModel } from '../status/models.js';

const router = Router(); const base = '/:workspaceId/reliability';
router.use(base, requireAuth, requireWorkspaceRole('owner', 'admin', 'member'));
for (const key of ['workspaceId', 'serviceId', 'dependencyId', 'sloId', 'monitorId']) router.param(key, (_req, _res, next, value) => statusIdSchema.safeParse(value).success ? next() : next(new IncidentError(400, 'Invalid identifier')));
const parse = <T extends z.ZodTypeAny>(schema: T, value: unknown): z.output<T> => { const result = schema.safeParse(value); assertIncident(result.success, 400, 'Invalid reliability request'); return result.data; };
const scope = (request: Request) => ({ workspaceId: request.params.workspaceId });
const actor = (request: Request) => request.auth!.userId;
const admin = (request: Request) => assertIncident(['owner', 'admin'].includes(request.workspaceMembership!.role), 403, 'Administrator access required');
const activity = (request: Request, entityId: string, action: string) => ActivityModel.create({ workspaceId: request.params.workspaceId, actorId: actor(request), entityType: 'reliability', entityId, action, metadata: {} });
const validateServiceRefs = async (request: Request, input: z.infer<typeof serviceInputSchema>) => {
  assertIncident(await WorkspaceMemberModel.countDocuments({ workspaceId: request.params.workspaceId, userId: { $in: input.ownerIds }, disabled: { $ne: true } }) === new Set(input.ownerIds).size, 400, 'Active workspace owners required');
  assertIncident(await UserModel.countDocuments({ _id: { $in: input.ownerIds }, status: 'active' }) === new Set(input.ownerIds).size, 400, 'Active workspace owners required');
  assertIncident(await ProjectModel.countDocuments({ workspaceId: request.params.workspaceId, _id: { $in: input.projectIds }, status: 'active' }) === new Set(input.projectIds).size, 400, 'Workspace projects required');
};
const serviceContract = (service: InstanceType<typeof ServiceModel>) => ({ ...service.toObject(), ownerIds: service.ownerIds.map(String), projectIds: service.projectIds.map(String) });
const sloContract = (slo: InstanceType<typeof ServiceLevelObjectiveModel>) => ({ ...slo.toObject(), serviceId: String(slo.serviceId), dataSource: { ...slo.dataSource, ...(slo.dataSource?.sourceId ? { sourceId: String(slo.dataSource.sourceId) } : {}) }, burnRateAlerts: (slo.burnRateAlerts ?? []).map((item) => ({ ...item, ...(item.escalationPolicyId ? { escalationPolicyId: String(item.escalationPolicyId) } : {}) })) });
const monitorContract = (monitor: InstanceType<typeof SyntheticMonitorModel>) => ({ ...monitor.toObject(), serviceId: String(monitor.serviceId), sloId: monitor.sloId ? String(monitor.sloId) : null });
const rejectUnsupportedBurnAlerts = (input: { burnRateAlerts?: unknown[] }) => assertIncident(!input.burnRateAlerts?.length, 400, 'Burn-rate alert delivery is not configured');
const refreshWorkspaceEvaluations = async (workspaceId: string) => {
  const evaluatedAt = new Date(Math.floor(Date.now() / 60000) * 60000);
  let after: mongoose.Types.ObjectId | undefined;
  for (;;) {
    const slos = await ServiceLevelObjectiveModel.find({ workspaceId, archivedAt: null, enabled: true, ...(after ? { _id: { $gt: after } } : {}) }).sort({ _id: 1 }).limit(100);
    for (let offset = 0; offset < slos.length; offset += 20) await Promise.all(slos.slice(offset, offset + 20).map((slo) => storeEvaluation(workspaceId, slo, evaluatedAt)));
    if (slos.length < 100) break;
    after = slos.at(-1)!._id;
  }
};
const archiveService = async (workspaceId: string, serviceId: string, actorId: string) => {
  const session = await mongoose.startSession();
  try {
    return await session.withTransaction(async () => {
      const service = await ServiceModel.findOneAndUpdate({ workspaceId, _id: serviceId, archivedAt: null }, { $set: { archivedAt: new Date(), lifecycle: 'retired', updatedBy: actorId }, $inc: { version: 1 } }, { new: true, session });
      assertIncident(service, 404, 'Service not found');
      await Promise.all([
        ServiceLevelObjectiveModel.updateMany({ workspaceId, serviceId, archivedAt: null }, { $set: { enabled: false, archivedAt: new Date(), updatedBy: actorId } }, { session }),
        SyntheticMonitorModel.updateMany({ workspaceId, serviceId, archivedAt: null }, { $set: { enabled: false, archivedAt: new Date(), updatedBy: actorId }, $unset: { leaseOwner: 1, leaseExpiresAt: 1 } }, { session }),
        ServiceDependencyModel.updateMany({ workspaceId, $or: [{ upstreamServiceId: serviceId }, { downstreamServiceId: serviceId }], archivedAt: null }, { $set: { enabled: false, archivedAt: new Date() } }, { session }),
      ]);
      return service;
    });
  } finally { await session.endSession(); }
};
const countServicesWithoutActiveOwners = async (workspaceId: string) => {
  const memberships = await WorkspaceMemberModel.find({ workspaceId, disabled: { $ne: true } }).select('userId').lean();
  const activeUsers = await UserModel.find({ _id: { $in: memberships.map((item) => item.userId) }, status: 'active' }).select('_id').lean();
  return ServiceModel.countDocuments({ workspaceId, archivedAt: null, ownerIds: { $not: { $elemMatch: { $in: activeUsers.map((item) => item._id) } } } });
};
router.get(`${base}/services`, async (req, res) => { const q = parse(reliabilityQuerySchema, req.query); res.json({ services: await ServiceModel.find({ ...scope(req), archivedAt: null }).sort({ name: 1 }).skip((q.page - 1) * q.limit).limit(q.limit) }); });
router.post(`${base}/services`, async (req, res) => { admin(req); const input = parse(serviceInputSchema, req.body); await validateServiceRefs(req, input); try { const service = await ServiceModel.create({ ...scope(req), ...input, slug: normalizeServiceSlug(input.slug), createdBy: actor(req), updatedBy: actor(req), archivedAt: null }); await activity(req, service.id, 'service.created'); res.status(201).json({ service }); } catch (error) { if ((error as { code?: number }).code === 11000) throw new IncidentError(409, 'Service slug already exists'); throw error; } });
router.get(`${base}/services/:serviceId`, async (req, res) => { const service = await ServiceModel.findOne({ ...scope(req), _id: req.params.serviceId, archivedAt: null }); assertIncident(service, 404, 'Service not found'); res.json({ service }); });
router.patch(`${base}/services/:serviceId`, async (req, res) => { admin(req); const input = parse(serviceInputSchema.partial(), req.body); const service = await ServiceModel.findOne({ ...scope(req), _id: req.params.serviceId, archivedAt: null }); assertIncident(service, 404, 'Service not found'); const merged = serviceInputSchema.parse({ ...serviceContract(service), ...input }); await validateServiceRefs(req, merged); Object.assign(service, input, input.slug ? { slug: normalizeServiceSlug(input.slug) } : {}, { updatedBy: actor(req), version: service.version + 1 }); await service.save(); await activity(req, service.id, 'service.updated'); res.json({ service }); });
router.delete(`${base}/services/:serviceId`, async (req, res) => { admin(req); const service = await archiveService(req.params.workspaceId, req.params.serviceId, actor(req)); await activity(req, service.id, 'service.archived'); res.status(204).end(); });
router.get(`${base}/dependencies`, async (req, res) => res.json({ dependencies: await ServiceDependencyModel.find({ ...scope(req), archivedAt: null }).limit(500) }));
router.post(`${base}/dependencies`, async (req, res) => { admin(req); const input = parse(dependencyInputSchema, req.body); const session = await mongoose.startSession(); let dependencyId: string | null = null; try { await session.withTransaction(async () => { await ReliabilityGraphLockModel.updateOne(scope(req), { $inc: { revision: 1 }, $setOnInsert: scope(req) }, { upsert: true, session }); assertIncident(await ServiceModel.countDocuments({ ...scope(req), _id: { $in: [input.upstreamServiceId, input.downstreamServiceId] }, archivedAt: null }).session(session) === 2, 400, 'Workspace services required'); assertIncident(!(await wouldCreateCycle(req.params.workspaceId, input.upstreamServiceId, input.downstreamServiceId, session)), 409, 'Dependency cycle detected'); const dependency = await ServiceDependencyModel.findOneAndUpdate({ ...scope(req), upstreamServiceId: input.upstreamServiceId, downstreamServiceId: input.downstreamServiceId }, { $set: { ...input, archivedAt: null, createdBy: actor(req) } }, { upsert: true, new: true, session }); dependencyId = dependency.id; }); } catch (error) { if ((error as { code?: number }).code === 11000) throw new IncidentError(409, 'Dependency already exists'); throw error; } finally { await session.endSession(); } assertIncident(dependencyId, 500, 'Dependency creation failed'); const dependency = await ServiceDependencyModel.findById(dependencyId); assertIncident(dependency, 500, 'Dependency creation failed'); await activity(req, dependency.id, 'service.dependencyChanged'); res.status(201).json({ dependency }); });
router.delete(`${base}/dependencies/:dependencyId`, async (req, res) => { admin(req); const dependency = await ServiceDependencyModel.findOneAndUpdate({ ...scope(req), _id: req.params.dependencyId, archivedAt: null }, { $set: { archivedAt: new Date(), enabled: false } }, { new: true }); assertIncident(dependency, 404, 'Dependency not found'); await activity(req, dependency.id, 'service.dependencyChanged'); res.status(204).end(); });
router.get(`${base}/services/:serviceId/impact`, async (req, res) => { assertIncident(await ServiceModel.exists({ ...scope(req), _id: req.params.serviceId, archivedAt: null }), 404, 'Service not found'); const direction = req.query.direction === 'downstream' ? 'downstream' : 'upstream'; res.json(await dependencyImpact(req.params.workspaceId, req.params.serviceId, direction)); });
const targetModels = { statusComponent: StatusComponentModel, incident: IncidentModel, alert: AlertModel, escalationPolicy: PolicyModel, project: ProjectModel } as const;
router.post(`${base}/relationships`, async (req, res) => { admin(req); const input = parse(relationshipInputSchema, req.body); assertIncident(await ServiceModel.exists({ ...scope(req), _id: input.serviceId, archivedAt: null }), 400, 'Workspace service required'); assertIncident(await targetModels[input.targetType].exists({ workspaceId: req.params.workspaceId, _id: input.targetId }), 400, 'Workspace target required'); try { const relationship = await ServiceRelationshipModel.create({ ...scope(req), ...input, createdBy: actor(req), archivedAt: null }); await activity(req, relationship.id, 'service.relationshipCreated'); res.status(201).json({ relationship }); } catch (error) { if ((error as { code?: number }).code === 11000) throw new IncidentError(409, 'Relationship already exists'); throw error; } });
router.get(`${base}/services/:serviceId/relationships`, async (req, res) => res.json({ relationships: await ServiceRelationshipModel.find({ ...scope(req), serviceId: req.params.serviceId, archivedAt: null }).limit(200) }));
router.get(`${base}/slos`, async (req, res) => res.json({ slos: await ServiceLevelObjectiveModel.find({ ...scope(req), archivedAt: null }).sort({ updatedAt: -1 }).limit(500) }));
router.post(`${base}/slos`, async (req, res) => { admin(req); const input = parse(sloInputSchema, req.body); rejectUnsupportedBurnAlerts(input); assertIncident(await ServiceModel.exists({ ...scope(req), _id: input.serviceId, archivedAt: null }), 400, 'Workspace service required'); assertIncident(await ServiceLevelObjectiveModel.countDocuments({ ...scope(req), serviceId: input.serviceId, archivedAt: null }) < 50, 409, 'Service SLO limit reached'); const slo = await ServiceLevelObjectiveModel.create({ ...scope(req), ...input, objectiveKey: randomUUID(), version: 1, createdBy: actor(req), updatedBy: actor(req), archivedAt: null }); await activity(req, slo.id, 'slo.created'); res.status(201).json({ slo }); });
router.patch(`${base}/slos/:sloId`, async (req, res) => { admin(req); if (req.body?.burnRateAlerts) rejectUnsupportedBurnAlerts(req.body); const session = await mongoose.startSession(); let createdId: string | null = null; try { await session.withTransaction(async () => { const old = await ServiceLevelObjectiveModel.findOne({ ...scope(req), _id: req.params.sloId, archivedAt: null }).session(session); assertIncident(old, 404, 'SLO not found'); const input = parse(sloInputSchema, { ...sloContract(old), ...req.body }); assertIncident(await ServiceModel.exists({ ...scope(req), _id: input.serviceId, archivedAt: null }).session(session), 400, 'Workspace service required'); const archived = await ServiceLevelObjectiveModel.updateOne({ _id: old._id, archivedAt: null, version: old.version }, { $set: { archivedAt: new Date(), enabled: false } }, { session }); assertIncident(archived.modifiedCount, 409, 'SLO changed concurrently'); const [created] = await ServiceLevelObjectiveModel.create([{ ...scope(req), ...input, objectiveKey: old.objectiveKey, version: old.version + 1, createdBy: old.createdBy, updatedBy: actor(req), archivedAt: null }], { session }); assertIncident(created, 500, 'SLO version update failed'); createdId = created.id; await SyntheticMonitorModel.updateMany({ ...scope(req), sloId: old._id, archivedAt: null }, { $set: { sloId: created._id, serviceId: created.serviceId }, $inc: { configVersion: 1 }, $unset: { leaseOwner: 1, leaseExpiresAt: 1 } }, { session }); }); } finally { await session.endSession(); } assertIncident(createdId, 500, 'SLO version update failed'); const slo = await ServiceLevelObjectiveModel.findById(createdId); assertIncident(slo, 500, 'SLO version update failed'); await activity(req, slo.id, 'slo.updated'); res.json({ slo }); });
router.delete(`${base}/slos/:sloId`, async (req, res) => { admin(req); const slo = await ServiceLevelObjectiveModel.findOneAndUpdate({ ...scope(req), _id: req.params.sloId, archivedAt: null }, { $set: { archivedAt: new Date(), enabled: false, updatedBy: actor(req) } }, { new: true }); assertIncident(slo, 404, 'SLO not found'); await activity(req, slo.id, 'slo.archived'); res.status(204).end(); });
router.get(`${base}/slos/:sloId/versions`, async (req, res) => { const current = await ServiceLevelObjectiveModel.findOne({ ...scope(req), _id: req.params.sloId }); assertIncident(current, 404, 'SLO not found'); res.json({ versions: await ServiceLevelObjectiveModel.find({ ...scope(req), objectiveKey: current.objectiveKey }).sort({ version: -1 }).limit(100) }); });
router.post(`${base}/sli`, async (req, res) => { admin(req); const parsedInput = parse(sliBatchSchema, req.body); const input = { samples: parsedInput.samples.map((sample) => ({ ...sample, serviceId: sample.serviceId.toLowerCase(), sloId: sample.sloId.toLowerCase() })) }; const now = Date.now(); const sloIds = [...new Set(input.samples.map((x) => x.sloId))]; const slos = await ServiceLevelObjectiveModel.find({ ...scope(req), _id: { $in: sloIds }, archivedAt: null, enabled: true }).limit(100); const byId = new Map(slos.map((x) => [x.id, x])); assertIncident(slos.length === sloIds.length, 400, 'Active workspace SLOs required'); let accepted = 0; for (const sample of input.samples) { const timestamp = new Date(sample.timestamp); assertIncident(timestamp.getTime() <= now + 300000 && timestamp.getTime() >= now - 7 * 86400_000, 400, 'Sample timestamp outside ingestion window'); const slo = byId.get(sample.sloId)!; assertIncident(slo.dataSource?.type === 'api', 400, 'SLO does not accept API samples'); assertIncident(String(slo.serviceId) === sample.serviceId, 400, 'Sample service does not own SLO'); const result = await SliSampleModel.updateOne({ workspaceId: req.params.workspaceId, idempotencyKey: sample.idempotencyKey }, { $setOnInsert: { ...sample, workspaceId: req.params.workspaceId, timestamp, bucketAt: new Date(Math.floor(timestamp.getTime() / 300000) * 300000), sloVersion: slo.version, source: 'api', expiresAt: new Date(now + 400 * 86400_000) } }, { upsert: true }); accepted += result.upsertedCount; } res.status(202).json({ accepted, duplicates: input.samples.length - accepted }); });
router.get(`${base}/slos/:sloId/evaluation`, async (req, res) => { const slo = await ServiceLevelObjectiveModel.findOne({ ...scope(req), _id: req.params.sloId, archivedAt: null }); assertIncident(slo, 404, 'SLO not found'); res.json({ evaluation: await storeEvaluation(req.params.workspaceId, slo) }); });
router.get(`${base}/slos/:sloId/history`, async (req, res) => { const q = parse(reliabilityQuerySchema, req.query); res.json({ evaluations: await SloEvaluationModel.find({ ...scope(req), sloId: req.params.sloId }).sort({ windowEnd: -1 }).skip((q.page - 1) * q.limit).limit(q.limit) }); });
router.get(`${base}/monitors`, async (req, res) => { const q = parse(reliabilityQuerySchema, req.query); res.json({ monitors: await SyntheticMonitorModel.find({ ...scope(req), archivedAt: null }).select('-secretCiphertext -secretKeyVersion').sort({ _id: 1 }).skip((q.page - 1) * q.limit).limit(q.limit) }); });
router.post(`${base}/monitors`, async (req, res) => { admin(req); const input = parse(monitorInputSchema, req.body); assertSafeMonitorUrl(input.url); assertIncident(await ServiceModel.exists({ ...scope(req), _id: input.serviceId, archivedAt: null }), 400, 'Workspace service required'); const id = new mongoose.Types.ObjectId(); if (input.sloId) { const slo = await ServiceLevelObjectiveModel.findOne({ ...scope(req), _id: input.sloId, serviceId: input.serviceId, archivedAt: null, enabled: true, 'dataSource.type': 'synthetic' }); assertIncident(slo && (!slo.dataSource?.sourceId || slo.dataSource.sourceId === String(id)), 400, 'Compatible synthetic SLO required'); } const secret = input.secretHeaders ? encryptSecret(JSON.stringify(input.secretHeaders), req.params.workspaceId, String(id)) : null; const monitor = await SyntheticMonitorModel.create({ _id: id, ...scope(req), ...input, secretHeaders: undefined, secretCiphertext: secret?.credentials, secretKeyVersion: secret?.keyVersion, nextRunAt: new Date(), createdBy: actor(req), updatedBy: actor(req), archivedAt: null }); await activity(req, monitor.id, 'monitor.created'); res.status(201).json({ monitor: await SyntheticMonitorModel.findById(monitor._id) }); });
router.patch(`${base}/monitors/:monitorId`, async (req, res) => { admin(req); const monitor = await SyntheticMonitorModel.findOne({ ...scope(req), _id: req.params.monitorId, archivedAt: null }).select('+secretCiphertext +secretKeyVersion'); assertIncident(monitor, 404, 'Monitor not found'); const input = parse(monitorInputSchema, { ...monitorContract(monitor), ...req.body }); assertSafeMonitorUrl(input.url); assertIncident(await ServiceModel.exists({ ...scope(req), _id: input.serviceId, archivedAt: null }), 400, 'Workspace service required'); if (input.enabled && input.sloId) { const slo = await ServiceLevelObjectiveModel.findOne({ ...scope(req), _id: input.sloId, serviceId: input.serviceId, archivedAt: null, enabled: true, 'dataSource.type': 'synthetic' }); assertIncident(slo && (!slo.dataSource?.sourceId || slo.dataSource.sourceId === monitor.id), 400, 'Compatible synthetic SLO required'); } const secretHeaders = input.secretHeaders; delete input.secretHeaders; const changes: Record<string, unknown> = { ...input, updatedBy: actor(req), ...(input.enabled ? { nextRunAt: new Date() } : {}) }; if (secretHeaders) { const secret = encryptSecret(JSON.stringify(secretHeaders), req.params.workspaceId, monitor.id); changes.secretCiphertext = secret.credentials; changes.secretKeyVersion = secret.keyVersion; } const updated = await SyntheticMonitorModel.findOneAndUpdate({ _id: monitor._id, configVersion: monitor.configVersion }, { $set: changes, $inc: { configVersion: 1 }, $unset: { leaseOwner: 1, leaseExpiresAt: 1 } }, { new: true }); assertIncident(updated, 409, 'Monitor changed concurrently'); await activity(req, updated.id, 'monitor.updated'); res.json({ monitor: updated }); });
router.delete(`${base}/monitors/:monitorId`, async (req, res) => { admin(req); const monitor = await SyntheticMonitorModel.findOneAndUpdate({ ...scope(req), _id: req.params.monitorId, archivedAt: null }, { $set: { archivedAt: new Date(), enabled: false, updatedBy: actor(req) }, $unset: { secretCiphertext: 1, secretKeyVersion: 1 } }, { new: true }); assertIncident(monitor, 404, 'Monitor not found'); await activity(req, monitor.id, 'monitor.archived'); res.status(204).end(); });
router.post(`${base}/monitors/:monitorId/test`, async (req, res) => { admin(req); const monitor = await SyntheticMonitorModel.findOne({ ...scope(req), _id: req.params.monitorId, archivedAt: null }); assertIncident(monitor, 404, 'Monitor not found'); assertIncident(monitor.enabled, 409, 'Enable the monitor before testing external traffic'); await SyntheticMonitorModel.updateOne({ _id: monitor._id }, { $set: { nextRunAt: new Date() } }); const executed = await processReliabilityWork(new Date(), `manual:${actor(req)}`, undefined, { workspaceId: req.params.workspaceId, monitorId: monitor.id }); assertIncident(executed, 409, 'Monitor is already running'); res.status(202).json({ message: 'Test executed; inspect sanitized history.' }); });
router.get(`${base}/monitors/:monitorId/history`, async (req, res) => { const q = parse(reliabilityQuerySchema, req.query); assertIncident(await SyntheticMonitorModel.exists({ ...scope(req), _id: req.params.monitorId }), 404, 'Monitor not found'); res.json({ runs: await SyntheticMonitorRunModel.find({ ...scope(req), monitorId: req.params.monitorId }).sort({ scheduledAt: -1 }).skip((q.page - 1) * q.limit).limit(q.limit) }); });
router.get(`${base}/metrics`, async (req, res) => { await refreshWorkspaceEvaluations(req.params.workspaceId); const [lifecycles, criticalities, ownerless, sloStates, monitorStates] = await Promise.all([ServiceModel.aggregate([{ $match: { workspaceId: new mongoose.Types.ObjectId(req.params.workspaceId), archivedAt: null } }, { $group: { _id: '$lifecycle', count: { $sum: 1 } } }]), ServiceModel.aggregate([{ $match: { workspaceId: new mongoose.Types.ObjectId(req.params.workspaceId), archivedAt: null } }, { $group: { _id: '$criticality', count: { $sum: 1 } } }]), countServicesWithoutActiveOwners(req.params.workspaceId), SloEvaluationModel.aggregate([{ $match: { workspaceId: new mongoose.Types.ObjectId(req.params.workspaceId) } }, { $sort: { windowEnd: -1 } }, { $group: { _id: '$sloId', state: { $first: '$state' }, remainingBudget: { $first: '$remainingBudget' } } }, { $lookup: { from: ServiceLevelObjectiveModel.collection.name, localField: '_id', foreignField: '_id', as: 'activeSlo' } }, { $unwind: '$activeSlo' }, { $match: { 'activeSlo.archivedAt': null, 'activeSlo.enabled': true } }, { $group: { _id: '$state', count: { $sum: 1 }, meanRemainingBudget: { $avg: '$remainingBudget' } } }]), SyntheticMonitorModel.aggregate([{ $match: { workspaceId: new mongoose.Types.ObjectId(req.params.workspaceId), archivedAt: null } }, { $group: { _id: '$health', count: { $sum: 1 } } }])]); res.json({ servicesByLifecycle: lifecycles, servicesByCriticality: criticalities, servicesWithoutOwners: ownerless, sloStates, monitorStates, notice: 'Unknown and insufficient data are excluded from healthy compliance.' }); });

export default router;
