import { randomUUID } from 'node:crypto';

import { MongoMemoryReplSet } from 'mongodb-memory-server';
import mongoose from 'mongoose';
import request from 'supertest';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';

import { createApp } from './app.js';
import { issueTokens } from './auth/tokens.js';
import { IntelligenceCheckpointModel, IntelligenceEvaluationModel, IntelligencePolicyModel, IntelligenceRecommendationModel, OperationalSignalModel } from './intelligence/models.js';
import { processIntelligenceWork, reconcileWorkspace } from './intelligence/service.js';
import { IncidentModel } from './models/Incident.js';
import { ProjectModel } from './models/Project.js';
import { TaskModel } from './models/Task.js';
import { UserModel } from './models/User.js';
import { WorkspaceModel } from './models/Workspace.js';
import { WorkspaceMemberModel } from './models/WorkspaceMember.js';
import { AlertModel } from './oncall/models.js';
import { ServiceModel } from './reliability/models.js';

const app=createApp(); let mongo:MongoMemoryReplSet;
beforeAll(async()=>{process.env.AUTOMATION_ENCRYPTION_KEYS=JSON.stringify({'1':'ab'.repeat(32)});process.env.STATUS_SUBSCRIBER_LOOKUP_KEY='cd'.repeat(32);mongo=await MongoMemoryReplSet.create({replSet:{count:1}});await mongoose.connect(mongo.getUri());await Promise.all(Object.values(mongoose.models).map(model=>model.init()));},180000);
beforeEach(async()=>{for(const collection of Object.values(mongoose.connection.collections))await collection.deleteMany({});});
afterAll(async()=>{await mongoose.disconnect();await mongo.stop();delete process.env.AUTOMATION_ENCRYPTION_KEYS;delete process.env.STATUS_SUBSCRIBER_LOOKUP_KEY;},30000);
const fixture=async()=>{const [owner,member,outsider,suspended]=await UserModel.create(['owner','member','outsider','suspended'].map(name=>({name,email:`${name}@intelligence.test`,passwordHash:'unused',status:name==='suspended'?'suspended':'active'})));const workspace=await WorkspaceModel.create({name:'Ops',createdBy:owner!.id});const other=await WorkspaceModel.create({name:'Other',createdBy:outsider!.id});await WorkspaceMemberModel.create([{workspaceId:workspace.id,userId:owner!.id,role:'owner'},{workspaceId:workspace.id,userId:member!.id,role:'member'},{workspaceId:workspace.id,userId:suspended!.id,role:'admin'},{workspaceId:other.id,userId:outsider!.id,role:'owner'}]);const project=await ProjectModel.create({workspaceId:workspace.id,name:'Product',description:'',status:'active',color:'#123456',createdBy:owner!.id});const cookie=async(user=owner!)=>`accessToken=${(await issueTokens(user.id)).accessToken}`;return{owner:owner!,member:member!,outsider:outsider!,suspended:suspended!,workspace,other,project,cookie};};

describe('operational intelligence integration',()=>{
  it('deduplicates concurrent reconciliation and resolves a source lifecycle change',async()=>{const f=await fixture();const due=new Date(Date.now()-86400_000);const task=await TaskModel.create({workspaceId:f.workspace.id,projectId:f.project.id,title:'Overdue',status:'todo',priority:'urgent',assigneeId:f.member.id,dueDate:due,position:0,createdBy:f.owner.id});await Promise.all([reconcileWorkspace(f.workspace.id),reconcileWorkspace(f.workspace.id)]);expect(await OperationalSignalModel.countDocuments({workspaceId:f.workspace.id,sourceId:task.id,state:'active'})).toBe(1);expect(await IntelligenceRecommendationModel.countDocuments({workspaceId:f.workspace.id})).toBe(1);await TaskModel.updateOne({_id:task._id},{$set:{status:'done'}});await reconcileWorkspace(f.workspace.id,new Date(Date.now()+1));expect(await OperationalSignalModel.countDocuments({workspaceId:f.workspace.id,sourceId:task.id,state:'resolved'})).toBe(1);expect((await IntelligenceRecommendationModel.findOne({workspaceId:f.workspace.id}))?.state).toBe('stale');await TaskModel.updateOne({_id:task._id},{$set:{status:'todo'}});const recurrenceAt=new Date(Date.now()+2);await reconcileWorkspace(f.workspace.id,recurrenceAt);const recurring=await OperationalSignalModel.findOne({workspaceId:f.workspace.id,sourceId:task.id}).orFail();expect(recurring.state).toBe('active');expect(recurring.detectedAt?.getTime()).toBe(recurrenceAt.getTime());expect(recurring.recurrenceCount).toBe(1);});
  it('enforces personal assignment, workspace roles, tenant isolation and suspended users',async()=>{const f=await fixture();await TaskModel.create({workspaceId:f.workspace.id,projectId:f.project.id,title:'Assigned',status:'todo',priority:'high',assigneeId:f.member.id,dueDate:new Date(Date.now()-1000),position:0,createdBy:f.owner.id});await reconcileWorkspace(f.workspace.id);const memberCookie=await f.cookie(f.member);expect((await request(app).get(`/api/workspaces/${f.workspace.id}/intelligence/queue/personal`).set('Cookie',memberCookie)).body.total).toBe(1);await request(app).get(`/api/workspaces/${f.workspace.id}/intelligence/queue/workspace`).set('Cookie',memberCookie).expect(403);await request(app).get(`/api/workspaces/${f.other.id}/intelligence/signals/${(await OperationalSignalModel.findOne())!._id}`).set('Cookie',await f.cookie(f.outsider)).expect(404);await request(app).get(`/api/workspaces/${f.workspace.id}/intelligence/queue/personal`).set('Cookie',await f.cookie(f.suspended)).expect(401);});
  it('keeps policy versions immutable and restricts activation to administrators',async()=>{const f=await fixture();const active=(await request(app).get(`/api/workspaces/${f.workspace.id}/intelligence/policies/active`).set('Cookie',await f.cookie()).expect(200)).body.policy;const body={...active.configuration,name:'Urgent operations',expectedActiveVersion:active.version};const created=(await request(app).post(`/api/workspaces/${f.workspace.id}/intelligence/policies`).set('Cookie',await f.cookie()).send(body).expect(201)).body.policy;await request(app).post(`/api/workspaces/${f.workspace.id}/intelligence/policies/${created._id}/activate`).set('Cookie',await f.cookie(f.member)).send({expectedActiveVersion:1,operationId:randomUUID()}).expect(403);await request(app).post(`/api/workspaces/${f.workspace.id}/intelligence/policies/${created._id}/activate`).set('Cookie',await f.cookie()).send({expectedActiveVersion:1,operationId:randomUUID()}).expect(200);expect(await IntelligencePolicyModel.countDocuments({workspaceId:f.workspace.id})).toBe(2);expect((await IntelligencePolicyModel.findOne({_id:active._id}))?.active).toBe(false);});
  it('rejects stale feedback and makes operation receipts idempotent',async()=>{const f=await fixture();await TaskModel.create({workspaceId:f.workspace.id,projectId:f.project.id,title:'Old',status:'todo',priority:'high',assigneeId:f.member.id,dueDate:new Date(Date.now()-1000),position:0,createdBy:f.owner.id});await reconcileWorkspace(f.workspace.id);const rec=await IntelligenceRecommendationModel.findOne().orFail();const operationId=randomUUID();await request(app).post(`/api/workspaces/${f.workspace.id}/intelligence/recommendations/${rec.id}/dismiss`).set('Cookie',await f.cookie(f.member)).send({operationId}).expect(200);await request(app).post(`/api/workspaces/${f.workspace.id}/intelligence/recommendations/${rec.id}/dismiss`).set('Cookie',await f.cookie(f.member)).send({operationId}).expect(200);rec.sourceVersion='obsolete';await rec.save();await request(app).post(`/api/workspaces/${f.workspace.id}/intelligence/recommendations/${rec.id}/accept`).set('Cookie',await f.cookie(f.member)).send({operationId:randomUUID()}).expect(409);});
  it('claims evaluation work once, recovers an expired lease and exposes bounded admin history',async()=>{const f=await fixture();const job=await IntelligenceEvaluationModel.create({workspaceId:f.workspace.id,sourceType:'reconciliation',sourceId:f.workspace.id,sourceRevision:'1',workKey:'one',status:'processing',availableAt:new Date(0),attemptCount:1,leaseOwner:'crashed',leaseExpiresAt:new Date(0)});await Promise.all([processIntelligenceWork(new Date(),'a'),processIntelligenceWork(new Date(),'b')]);const completed=await IntelligenceEvaluationModel.findById(job._id);expect(completed?.status).toBe('completed');expect(completed?.attemptCount).toBe(2);const response=await request(app).get(`/api/workspaces/${f.workspace.id}/intelligence/evaluations`).set('Cookie',await f.cookie()).expect(200);expect(response.body.evaluations.length).toBeGreaterThanOrEqual(1);expect(response.body.evaluations.find((item:{_id:string})=>item._id===job.id)?.leaseOwner).toBeUndefined();});
  it('does not refill recommendations after their source resolves',async()=>{const f=await fixture();const task=await TaskModel.create({workspaceId:f.workspace.id,projectId:f.project.id,title:'Capacity',status:'todo',priority:'high',dueDate:new Date(Date.now()-1000),position:0,createdBy:f.owner.id});await reconcileWorkspace(f.workspace.id);await IntelligenceRecommendationModel.updateOne({workspaceId:f.workspace.id},{$set:{state:'stale',staleReason:'capacity'}});await TaskModel.updateOne({_id:task._id},{$set:{status:'done'}});await reconcileWorkspace(f.workspace.id,new Date(Date.now()+1));const recommendation=await IntelligenceRecommendationModel.findOne({workspaceId:f.workspace.id}).orFail();expect(recommendation.state).toBe('stale');expect(await OperationalSignalModel.countDocuments({workspaceId:f.workspace.id,state:'active'})).toBe(0);});
  it('retires task priorities when their project is archived',async()=>{const f=await fixture();const task=await TaskModel.create({workspaceId:f.workspace.id,projectId:f.project.id,title:'Archived work',status:'todo',priority:'high',dueDate:new Date(Date.now()-1000),position:0,createdBy:f.owner.id});await reconcileWorkspace(f.workspace.id);expect(await OperationalSignalModel.countDocuments({workspaceId:f.workspace.id,sourceId:task.id,state:'active'})).toBe(1);await ProjectModel.updateOne({_id:f.project._id},{$set:{status:'archived'}});await reconcileWorkspace(f.workspace.id,new Date(Date.now()+1));expect(await OperationalSignalModel.countDocuments({workspaceId:f.workspace.id,sourceId:task.id,state:'active'})).toBe(0);expect((await IntelligenceRecommendationModel.findOne({workspaceId:f.workspace.id}))?.state).toBe('stale');await TaskModel.updateOne({_id:task._id},{$set:{status:'todo'}});const recurrenceAt=new Date(Date.now()+2);await reconcileWorkspace(f.workspace.id,recurrenceAt);const recurring=await OperationalSignalModel.findOne({workspaceId:f.workspace.id,sourceId:task.id}).orFail();expect(recurring.state).toBe('active');expect(recurring.detectedAt?.getTime()).toBe(recurrenceAt.getTime());expect(recurring.recurrenceCount).toBe(1);});
  it('retires signals excluded by policy even when their source type scan is incomplete',async()=>{const f=await fixture();const due=new Date(Date.now()-1000);await TaskModel.insertMany(Array.from({length:500},(_,index)=>({workspaceId:f.workspace.id,projectId:f.project.id,title:`Task ${index}`,status:'todo',priority:'high',dueDate:due,position:index,createdBy:f.owner.id})));await reconcileWorkspace(f.workspace.id);expect(await OperationalSignalModel.countDocuments({workspaceId:f.workspace.id,sourceType:'task.overdue',state:'active'})).toBeGreaterThan(0);const policy=await IntelligencePolicyModel.findOne({workspaceId:f.workspace.id,active:true}).orFail();policy.configuration={...policy.configuration,includedSignalTypes:(policy.configuration.includedSignalTypes as string[]).filter((type)=>type!=='task.overdue')};await policy.save();await reconcileWorkspace(f.workspace.id,new Date(Date.now()+1));expect(await OperationalSignalModel.countDocuments({workspaceId:f.workspace.id,sourceType:'task.overdue',state:'active'})).toBe(0);},120000);
  it('retires a superseded capacity recommendation and renews the evaluation lease during reconciliation',async()=>{const f=await fixture();const incident=await IncidentModel.create({workspaceId:f.workspace.id,incidentNumber:'INC-000001',title:'Major incident',severity:'sev1',status:'investigating',declaredBy:f.owner.id,declaredAt:new Date()});let renewals=0;await reconcileWorkspace(f.workspace.id,new Date(),async()=>{renewals++;});expect(renewals).toBeGreaterThan(1);await IntelligenceRecommendationModel.updateOne({workspaceId:f.workspace.id,type:'assignIncidentCommander'},{$set:{state:'stale',staleReason:'capacity'}});await IncidentModel.updateOne({_id:incident._id},{$set:{commanderId:f.owner._id,updatedAt:new Date(Date.now()+1000)}});await reconcileWorkspace(f.workspace.id,new Date(Date.now()+1001));expect((await IntelligenceRecommendationModel.findOne({workspaceId:f.workspace.id,type:'assignIncidentCommander'}))?.staleReason).toBe('source');expect((await IntelligenceRecommendationModel.findOne({workspaceId:f.workspace.id,type:'joinIncident'}))?.state).toBe('open');});
  it('scores service-linked alerts using current service criticality',async()=>{const f=await fixture();const [tier1,tier4]=await ServiceModel.create([{workspaceId:f.workspace.id,name:'Critical',slug:'critical',lifecycle:'active',criticality:'tier1',ownerIds:[f.owner._id],createdBy:f.owner._id,updatedBy:f.owner._id},{workspaceId:f.workspace.id,name:'Low',slug:'low',lifecycle:'active',criticality:'tier4',ownerIds:[f.owner._id],createdBy:f.owner._id,updatedBy:f.owner._id}]);const at=new Date();await AlertModel.create([{workspaceId:f.workspace.id,fingerprint:'critical-alert',title:'Critical alert',severity:'sev2',status:'open',firstReceivedAt:at,lastReceivedAt:at,correlationId:'critical',serviceId:tier1!.id,createdBy:f.owner._id},{workspaceId:f.workspace.id,fingerprint:'low-alert',title:'Low alert',severity:'sev2',status:'open',firstReceivedAt:at,lastReceivedAt:at,correlationId:'low',serviceId:tier4!.id,createdBy:f.owner._id}]);await reconcileWorkspace(f.workspace.id,at);const signals=await OperationalSignalModel.find({workspaceId:f.workspace.id,sourceType:'alert.unacknowledged'}).sort({score:-1});expect(signals).toHaveLength(2);expect(signals[0]!.score).toBeGreaterThan(signals[1]!.score!);expect(signals.map((signal)=>signal.scoreRevision)).toEqual(expect.arrayContaining([expect.stringContaining('service:')]));});
  it('resets the attempt budget for an administrative dead-letter retry',async()=>{const f=await fixture();const evaluation=await IntelligenceEvaluationModel.create({workspaceId:f.workspace.id,sourceType:'reconciliation',sourceId:f.workspace.id,sourceRevision:'failed',workKey:'failed',status:'dead',availableAt:new Date(0),attemptCount:5,error:'EVALUATION_FAILED'});const response=await request(app).post(`/api/workspaces/${f.workspace.id}/intelligence/evaluations/${evaluation.id}/retry`).set('Cookie',await f.cookie()).send({operationId:randomUUID()}).expect(202);expect(response.body.evaluation).toMatchObject({status:'pending',attemptCount:0});});
  it('bounds metrics ranges and never copies task narrative into safe signal facts',async()=>{const f=await fixture();await TaskModel.create({workspaceId:f.workspace.id,projectId:f.project.id,title:'Secret title',description:'private narrative',status:'todo',priority:'high',dueDate:new Date(Date.now()-1000),position:0,createdBy:f.owner.id});await reconcileWorkspace(f.workspace.id);const raw=JSON.stringify((await OperationalSignalModel.findOne())!.facts);expect(raw).not.toContain('Secret title');expect(raw).not.toContain('private narrative');await request(app).get(`/api/workspaces/${f.workspace.id}/intelligence/metrics?from=2025-01-01T00:00:00.000Z&to=2026-10-01T00:00:00.000Z`).set('Cookie',await f.cookie()).expect(400);});

  it('preserves task signals while a cursor advances through later batches',async()=>{const f=await fixture();const due=new Date(Date.now()-1000);const first=await TaskModel.create({workspaceId:f.workspace.id,projectId:f.project.id,title:'Earlier page',status:'todo',priority:'high',dueDate:due,position:0,createdBy:f.owner.id});await reconcileWorkspace(f.workspace.id);const later=await TaskModel.create({workspaceId:f.workspace.id,projectId:f.project.id,title:'Final page',status:'todo',priority:'high',dueDate:due,position:1,createdBy:f.owner.id});await IntelligenceCheckpointModel.updateOne({_id:'workspace:'+f.workspace.id},{$set:{cursor:first._id}});await reconcileWorkspace(f.workspace.id,new Date(Date.now()+1));expect(await OperationalSignalModel.countDocuments({workspaceId:f.workspace.id,sourceType:'task.overdue',state:'active'})).toBe(2);expect(await OperationalSignalModel.countDocuments({workspaceId:f.workspace.id,sourceId:first._id,state:'active'})).toBe(1);expect(await OperationalSignalModel.countDocuments({workspaceId:f.workspace.id,sourceId:later._id,state:'active'})).toBe(1);});
});
